<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.openprovenance.bookptm</groupId>
        <artifactId>book-ptm</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>template-intro1</artifactId>
    <packaging>jar</packaging>

    <name>template-intro1</name>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>


    <build>
        <plugins>
            <plugin>
                <groupId>org.openprovenance.prov</groupId>
                <artifactId>prov-toolbox-plugin</artifactId>
                <version>${prov.toolbox.version}</version>
                <executions>
                    <execution>
                        <id>convert.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-qualified</arg>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/triangle/usage-generation-derivation.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/usage-generation-derivation.svg</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>instantiate.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/triangle/usage-generation-derivation.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/add1.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/add1.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>convert2.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-qualified</arg>
                                <arg>-infile</arg>
                                <arg>target/add1.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/add1.svg</arg>
                            </args>
                        </configuration>
                    </execution>


                    <execution>
                        <id>instantiate2.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/triangle/usage-generation-derivation.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/integer-division.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/integer-division.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>convert3.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/integer-division.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/integer-division.svg</arg>
                            </args>
                        </configuration>
                    </execution>



                    <execution>
                        <id>instantiate3.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/integer-division.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/division-121-4.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/division-121-4.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>convert4.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/division-121-4.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/division-121-4.svg</arg>
                            </args>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
