<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.openprovenance.bookptm</groupId>
        <artifactId>book-ptm</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>template-intro1</artifactId>
    <packaging>jar</packaging>

    <name>template-intro1</name>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>


    <build>
        <plugins>
            <plugin>
                <groupId>org.openprovenance.prov</groupId>
                <artifactId>prov-toolbox-plugin</artifactId>
                <version>${prov.toolbox.version}</version>
                <executions>
                    <execution>
                        <id>schema.check.demo</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>validate-bindings</goal>
                        </goals>
                        <configuration>
                            <warning>false</warning>
                            <args>
                                <arg>src/main/resources/bindings/examples/add1.json</arg>
                                <arg>src/main/resources/bindings/triangle/integer-division.json</arg>
                                <arg>src/main/resources/bindings/examples/division-121-4.json</arg>
                                <arg>src/main/resources/bindings/general/file-compression.json</arg>
                                <arg>src/main/resources/bindings/primitive/file-entity.json</arg>
                                <arg>src/main/resources/bindings/primitive/attribution-with-optionality.json</arg>
                                <arg>src/main/resources/bindings/examples/derivation-e2-e0.json</arg>
                                <arg>src/main/resources/bindings/examples/derivation-e0-e1.json</arg>
                                <arg>src/main/resources/bindings/examples/derivation-e0-e1.json</arg>
                                <arg>src/main/resources/bindings/examples/derivation-e0-e2.json</arg>

                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>convert.triangle.usage.generation.derivation.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-qualified</arg>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/triangle/usage-generation-derivation.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/usage-generation-derivation.svg</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>instantiate.examples.add1.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/triangle/usage-generation-derivation.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/examples/add1.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/add1.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>convert.examples.add1.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-qualified</arg>
                                <arg>-infile</arg>
                                <arg>target/add1.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/add1.svg</arg>
                            </args>
                        </configuration>
                    </execution>


                    <execution>
                        <id>instantiate.triangle.integer.division.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/triangle/usage-generation-derivation.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/triangle/integer-division.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/integer-division.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>convert.triangle.integer.division.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/integer-division.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/integer-division.svg</arg>
                            </args>
                        </configuration>
                    </execution>



                    <execution>
                        <id>instantiate.examples.division.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/integer-division.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/examples/division-121-4.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/division-121-4.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>convert.examples.division.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/division-121-4.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/division-121-4.svg</arg>
                            </args>
                        </configuration>
                    </execution>


                    <execution>
                        <id>convert.general.unary.operation.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/general/unary-operation-with-agent.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/unary-operation-with-agent.svg</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>instantiate.general.file.compression.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/general/unary-operation-with-agent.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/general/file-compression.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/file-compression.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>convert.general.file.compression.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/file-compression.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/file-compression.svg</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>instantiate.example.file.compression.no.agent.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/file-compression.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/examples/file-compression-no-agent-no-prop.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/file-compression-no-agent-no-prop.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>convert.example.file.compression.no.agent.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/file-compression-no-agent-no-prop.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/file-compression-no-agent-no-prop.svg</arg>
                            </args>
                        </configuration>
                    </execution>



                    <execution>
                        <id>instantiate.general.file.compression.no.agent.no.prop.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/file-compression.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/examples/file-compression-no-agent-no-prop.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/file-compression-no-agent-no-prop.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>



                    <execution>
                        <id>instantiate.primitive.entity.file.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/primitive/entity-with-attribute.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/primitive/file-entity.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/file-entity.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>convert.primitive.entity.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/primitive/entity-with-attribute.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/entity-with-attribute.svg</arg>
                            </args>
                        </configuration>
                    </execution>


                    <execution>
                        <id>instantiate.example.entity.file100Gb.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/file-entity.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/examples/file-100Gb.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/file-100Gb.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>convert.primitive.entity.file.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/file-entity.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/file-entity.svg</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>convert.example.entity.file100Gb.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/file-100Gb.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/file-100Gb.svg</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>instantiate.primitive.attribution-with-optionality.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/primitive/attribution.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/primitive/attribution-with-optionality.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/attribution-with-optionality.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>convert.primitive.attribution.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-qualified</arg>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/primitive/attribution.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/attribution.svg</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>convert.primitive.attribution-with-optionality.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-qualified</arg>
                                <arg>-infile</arg>
                                <arg>target/attribution-with-optionality.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/attribution-with-optionality.svg</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>instantiate.example.simple-derivation.e0-e1.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/primitive/simple-derivation.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/examples/derivation-e0-e1.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/derivation-e0-e1.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>instantiate.example.simple-derivation.e2-e0.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/primitive/simple-derivation.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/examples/derivation-e2-e0.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/derivation-e2-e0.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>instantiate.example.simple-derivation.e0-e2.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/primitive/simple-derivation.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/examples/derivation-e0-e2.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/derivation-e0-e2.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>instantiate.example.simple-derivation.e3-e2.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/primitive/simple-derivation.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/examples/derivation-e3-e2.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/derivation-e3-e2.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>convert.example.simple-derivation.e0-e1.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/derivation-e0-e1.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/derivation-e0-e1.svg</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>convert.example.simple-derivation.e0-e2.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/derivation-e0-e2.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/derivation-e0-e2.svg</arg>
                            </args>
                        </configuration>
                    </execution>



                    <execution>
                        <id>convert.example.simple-derivation.e2-e0.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/derivation-e2-e0.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/derivation-e2-e0.svg</arg>
                            </args>
                        </configuration>
                    </execution>


                    <execution>
                        <id>convert.example.simple-derivation.e3-e2.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/derivation-e3-e2.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/derivation-e3-e2.svg</arg>
                            </args>
                        </configuration>
                    </execution>



                    <execution>
                        <id>merge1.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-merge</arg>
                                <arg>src/main/resources/config/merge1.txt</arg>
                                <arg>-outfile</arg>
                                <arg>target/merge1.svg</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>merge2.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-merge</arg>
                                <arg>src/main/resources/config/merge2.txt</arg>
                                <arg>-outfile</arg>
                                <arg>target/merge2.svg</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                            <id>merge3.svg</id>
                            <phase>test</phase>
                            <goals>
                                <goal>provconvert</goal>
                            </goals>
                            <configuration>
                                <args>
                                    <arg>-merge</arg>
                                    <arg>src/main/resources/config/merge3.txt</arg>
                                    <arg>-outfile</arg>
                                    <arg>target/merge3.svg</arg>
                                </args>
                            </configuration>
                    </execution>

                    <execution>
                        <id>merge4.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-merge</arg>
                                <arg>src/main/resources/config/merge4.txt</arg>
                                <arg>-outfile</arg>
                                <arg>target/merge4.svg</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                            <id>merge5.svg</id>
                            <phase>test</phase>
                            <goals>
                                <goal>provconvert</goal>
                            </goals>
                            <configuration>
                                <args>
                                    <arg>-merge</arg>
                                    <arg>src/main/resources/config/merge5.txt</arg>
                                    <arg>-outfile</arg>
                                    <arg>target/merge5.svg</arg>
                                </args>
                            </configuration>
                    </execution>

                    <execution>
                            <id>merge6.svg</id>
                            <phase>test</phase>
                            <goals>
                                <goal>provconvert</goal>
                            </goals>
                            <configuration>
                                <args>
                                    <arg>-merge</arg>
                                    <arg>src/main/resources/config/merge6.txt</arg>
                                    <arg>-outfile</arg>
                                    <arg>target/merge6.svg</arg>
                                </args>
                            </configuration>
                    </execution>

                    <execution>
                        <id>test.ttf.schema</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>validate-ttb</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>src/main/resources/ttfs/config-triangles.json</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>entity0.svg</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/primitive/entity0.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/entity0.provn</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>exec.process.template</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>execute-ttb</goal>
                        </goals>
                        <configuration>
                            <inputBaseDir>${project.basedir}/src/main/resources</inputBaseDir>
                            <outputBaseDir>${project.build.directory}</outputBaseDir>
                            <configs>
                                <config>ttfs/config-triangles.json</config>
                            </configs>
                        </configuration>
                    </execution>

                    <execution>
                        <id>convert.new.triangle.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-qualified</arg>
                                <arg>-infile</arg>
                                <arg>target/generated-templates/triangle-ugd.provn</arg>
                                <arg>-outfile</arg>
                                <arg>target/triangle-ugd.svg</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>log2prov</id>
                        <phase>test</phase> <!-- later than concat-csv -->
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>${project.build.directory}/generated-templates/all.prov-csv</arg>
                                <arg>-log2prov</arg>
                                <arg>org.openprovenance.prov.template.library.ptm.Init</arg>
                                <arg>-outfile</arg>
                                <arg>target/all.svg</arg>
                            </args>
                        </configuration>
                    </execution>
                </executions>

                §<dependencies>
                    <dependency>
                        <groupId>org.openprovenance.prov</groupId>
                        <artifactId>prov-template-library</artifactId>
                        <version>${prov.toolbox.version}</version>
                    </dependency>
                </dependencies>

            </plugin>
            <!-- exec plugin to cat all files in target/generated-templates/prov-*.prov-csv into target/generated-templates/all.prov-csv -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>concat-csv</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>bash</executable>
                            <arguments>
                                <argument>-c</argument>
                                <argument>cat ${project.build.directory}/generated-templates/prov-*.prov-csv &gt; ${project.build.directory}/generated-templates/all.prov-csv</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>
</project>
