<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.openprovenance.bookptm</groupId>
        <artifactId>book-ptm</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>template-intro1</artifactId>
    <packaging>jar</packaging>

    <name>template-intro1</name>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>


    <build>
        <plugins>
            <plugin>
                <groupId>org.openprovenance.prov</groupId>
                <artifactId>prov-toolbox-plugin</artifactId>
                <version>${prov.toolbox.version}</version>
                <executions>
                    <execution>
                        <id>schema.check.demo</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>validate-bindings</goal>
                        </goals>
                        <configuration>
                            <warning>false</warning>
                            <args>
                                <arg>src/main/resources/bindings/examples/add1.json</arg>
                                <arg>src/main/resources/bindings/triangle/integer-division.json</arg>
                                <arg>src/main/resources/bindings/examples/division-121-4.json</arg>
                                <arg>src/main/resources/bindings/general/file-compression.json</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>convert.triangle.usage.generation.derivation.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-qualified</arg>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/triangle/usage-generation-derivation.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/usage-generation-derivation.svg</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>instantiate.examples.add1.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/triangle/usage-generation-derivation.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/examples/add1.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/add1.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>convert.examples.add1.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-qualified</arg>
                                <arg>-infile</arg>
                                <arg>target/add1.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/add1.svg</arg>
                            </args>
                        </configuration>
                    </execution>


                    <execution>
                        <id>instantiate.triangle.integer.division.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/triangle/usage-generation-derivation.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/triangle/integer-division.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/integer-division.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>convert.triangle.integer.division.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/integer-division.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/integer-division.svg</arg>
                            </args>
                        </configuration>
                    </execution>



                    <execution>
                        <id>instantiate.examples.division.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/integer-division.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/examples/division-121-4.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/division-121-4.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>convert.examples.division.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/division-121-4.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/division-121-4.svg</arg>
                            </args>
                        </configuration>
                    </execution>


                    <execution>
                        <id>convert.general.unary.operation.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/general/unary-operation-with-agent.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/unary-operation-with-agent.svg</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>instantiate.general.file.compression.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>src/main/resources/templates/general/unary-operation-with-agent.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/general/file-compression.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/file-compression.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>
                    <execution>
                        <id>convert.general.file.compression.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/file-compression.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/file-compression.svg</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>instantiate.example.file.compression.no.agent.jsonld</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/file-compression.jsonld</arg>
                                <arg>-bindings</arg>
                                <arg>src/main/resources/bindings/examples/file-compression-no-agent-no-prop.json</arg>
                                <arg>-outfile</arg>
                                <arg>target/file-compression-no-agent-no-prop.jsonld</arg>
                            </args>
                        </configuration>
                    </execution>

                    <execution>
                        <id>convert.general.file.compression.no.agent.no.prop.svg</id>
                        <phase>test</phase>
                        <goals>
                            <goal>provconvert</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-infile</arg>
                                <arg>target/file-compression-no-agent-no-prop.jsonld</arg>
                                <arg>-outfile</arg>
                                <arg>target/file-compression-no-agent-no-prop.svg</arg>
                            </args>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
