# Generated by ProvToolbox for template configuration 'File_transforming_compositeOutputs'
# by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateBean,
# in file CompilerBeanGenerator.java, at line 59

from past.util.Map import Map
from past.util.List import List


"""A composite bean for file_transforming_composite
 that only contains the outputs of this template."""
class File_transforming_compositeOutputs:
    def __init__(self, ID=None, bean=None, count=None, type=None, elements=None, consistsOf=None):
        self.isA = "org.openprovenance.templates.fs.FileTransformingComposite"
        self.ID = ID
        self.bean = bean
        self.count = count
        self.type = type
        self.elements = List()
        self.consistsOf = "org.openprovenance.book.fs.client.integrator.File_transformingOutputs"

    def toJSON(self):
        import json
        d = {('__elements' if k == 'elements' else k): v
            for k, v in self.__dict__.items()}
        return json.dumps(
            d,
            default=lambda o: o.__dict__,
            sort_keys=False,
            indent=4)

    def process(self, processor):
        # PAST generator method. Created by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateInvokeProcessor
        # in file CompilerBeanGenerator.java, at line 693
        return processor(self.bean, self.count, self.type, self.elements)
        pass

    def addElements(self, o):
        # Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateCompositeListExtender
        # in file CompilerBeanGenerator.java, at line 668
        self.elements.append(o)
        pass

    ID = None
    bean = None
    count = None
    type = None
