# Generated by ProvToolbox for template configuration 'File_approvingBuilder'
# by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonLib_aux,
# in file CompilerCommon.java, at line 100

from org.openprovenance.book.fs.client.common.File_approvingBean import File_approvingBean
from past.util.Map import Map
from past.util.List import List
from org.openprovenance.book.fs.client.integrator.File_approvingIntegratorBuilder import File_approvingIntegratorBuilder
from past.util.StringBuilder import StringBuilder


"""Builder class for file_approving"""
class File_approvingBuilder:
    def __init__(self):
        self.aArgs2CsVConverter = self.args2csv()
        self.aRecord2BeanConverter = lambda record:     self.record2bean(record)
        self.aRecord2CsvConverter = lambda record:     self.record2bean(record).process(self.aArgs2CsVConverter)
        self.aArgs2BeanConverter = lambda approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, start, end:     self.args2bean(approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, start, end)
        self.aBean2SqlConverter = self.bean2sql()
        self.aRecord2SqlConverter = lambda record:     self.record2bean(record).process(self.aBean2SqlConverter)

    def toJSON(self):
        import json
        d = {('__elements' if k == 'elements' else k): v
            for k, v in self.__dict__.items()}
        return json.dumps(
            d,
            default=lambda o: o.__dict__,
            sort_keys=False,
            indent=4)

    def getBaseRelations(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateBaseRelationsAccessor
        # in file CompilerCommon.java, at line 210
        return '["file","agent","score","approval_record","activity","method"]'
        pass

    def getName(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateNameAccessor
        # in file CompilerCommon.java, at line 377
        return "file_approving"
        pass

    def getSemanticType(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateGetSemanticTypeField
        # in file CompilerCommon.java, at line 395
        return 0
        pass

    def getFullyQualifiedName(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateFullyQualifiedNameAccessor
        # in file CompilerCommon.java, at line 409
        return "org.openprovenance.templates.fs.FileApproving"
        pass

    def getTemplateName(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateTemplateNameAccessor
        # in file CompilerCommon.java, at line 418
        return "org.openprovenance.templates.fs.FileApproving"
        pass

    def getCBindings(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCBindingsAccessor
        # in file CompilerCommon.java, at line 427
        return "org/openprovenance/cbindings/fs/file-approving.json"
        pass

    """Null method for composite
    @return the array of properties in order"""
    def getPropertyOrder(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generatePropertyOrderMethod
        # in file CompilerCommon.java, at line 437
        return self.propertyOrder
        pass

    """Logger method
    @param sb a StringBuffer
    @param __approved_pipeline The approved pipeline
    @param __filename The filename of the approved pipeline
    @param __pipeline The pipeline before approval
    @param __approval_record The approval record
    @param __score The score obtained through validation
    @param __approval_method The method to transform the file
    @param __manager The manager approving the ML pipeline
    @param __approving The activity of approving the pipeline
    @param __signature The approval's signature
    @param __path The actual path of the file
    @param __time Time when the filtered file is created
    @param __start Time when the transformation starts
    @param __end Time when the transformation ends"""
    def logFile_approving(self, sb, approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, start, end):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateLoggerMethod
        # in file CompilerCommon.java, at line 1101
        sb.append("org.openprovenance.templates.fs.FileApproving")
        sb.append(",")
        if approved_pipeline == 0:
            pass
        else:
            sb.append(approved_pipeline)
        sb.append(",")
        if filename == 0:
            pass
        else:
            sb.append(filename)
        sb.append(",")
        if pipeline == 0:
            pass
        else:
            sb.append(pipeline)
        sb.append(",")
        if approval_record == 0:
            pass
        else:
            sb.append(approval_record)
        sb.append(",")
        if score == 0:
            pass
        else:
            sb.append(score)
        sb.append(",")
        if approval_method == 0:
            pass
        else:
            sb.append(approval_method)
        sb.append(",")
        if manager == 0:
            pass
        else:
            sb.append(manager)
        sb.append(",")
        if approving == 0:
            pass
        else:
            sb.append(approving)
        sb.append(",")
        if signature == 0:
            pass
        else:
            sb.append(signature)
        sb.append(",")
        if path == 0:
            pass
        else:
            sb.append(path)
        sb.append(",")
        if time == 0:
            pass
        else:
            sb.append(time)
        sb.append(",")
        if start == 0:
            pass
        else:
            sb.append(start)
        sb.append(",")
        if end == 0:
            pass
        else:
            sb.append(end)
        pass

    """logFile_approving client side logging method
    @return $T"""
    def args2csv(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonCSVConverterMethod
        # in file CompilerCommon.java, at line 480
        return lambda approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, start, end:     self.funLambda0(approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, start, end)
        pass

    def getNodes(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonMethodGetNodes2
        # in file CompilerCommon.java, at line 1202
        return self.nodes
        pass

    def getSuccessors(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonMethodGetSuccessors
        # in file CompilerCommon.java, at line 1281
        return self.successors
        pass

    def getTypedSuccessors(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonMethodGetTypedSuccessors
        # in file CompilerCommon.java, at line 1308
        return self.successors2
        pass

    def newBean(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateNewBean
        # in file CompilerCommon.java, at line 2064
        bean = File_approvingBean()
        return bean
        pass

    def record2csv(self, record):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateRecordCsvProcessorMethod
        # in file CompilerCommon.java, at line 1269
        return aRecord2CsvConverter
        pass

    def isCompositeOf(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateIsCompositeOfMethod
        # in file CompilerCommon.java, at line 363
        return 0
        pass

    def getSQLInsert(self):
        # Generated by class org.openprovenance.prov.template.compiler.CompilerSQL, method generateSQLInsert
        # in file CompilerSQL.java, at line 259
        return self._sqlInsert1
        pass

    def getSQLInsertStatement(self):
        # Generated by class org.openprovenance.prov.template.compiler.CompilerSQL, method generateSQLInsertStatement
        # in file CompilerSQL.java, at line 272
        return "_sqlInsert1 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);"
        pass

    def getForeign(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonMethodGetForeign
        # in file CompilerCommon.java, at line 1295
        return foreignTables
        pass

    @staticmethod
    def getSuccessors():
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonMethod4static
        # in file CompilerCommon.java, at line 1324
        table = Map()
        table.put(1, [])
        table.put(3, [4, 1])
        table.put(4, [])
        table.put(5, [4, 1])
        table.put(6, [])
        table.put(7, [])
        table.put(8, [])
        return table
        pass

    """Apply method
    @param processor a transformer for this template
    @param record as an array of Objects
    @param <T> type variable for the result of processor
    @return an object of type $T"""
    def apply(self, processor, record):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateApplyMethod
        # in file CompilerCommon.java, at line 1043
        return self.record2bean(record)(processor)
        pass

    @staticmethod
    def getNodes():
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateGetNodeStatic
        # in file CompilerCommon.java, at line 1181
        return [1, 3, 4, 5, 6, 7, 8]
        pass

    @staticmethod
    def getTypedSuccessors():
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateGetTypedSuccessorsStatic
        # in file CompilerCommon.java, at line 1722
        table = Map()
        table.put(1, [])
        table.put(3, [4, 9, 1, 9])
        table.put(4, [])
        table.put(5, [4, 9, 1, 9])
        table.put(6, [])
        table.put(7, [1, 11, 4, 11])
        table.put(8, [])
        return table
        pass

    """Converter to bean of type $T for template ClassName{packge='org.openprovenance.book.fs.client.common', simpleName='File_approvingBean'}.
    @param record an array of objects
    @return a bean"""
    def record2bean(self, record):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateFactoryMethodToBeanWithArray
        # in file CompilerCommon.java, at line 2007
        bean = File_approvingBean()
        bean.approved_pipeline = 0 if record[1] == 0 else int.valueOf(record[1]) if isinstance(record[1], str) else record[1]
        bean.filename = record[2]
        bean.pipeline = 0 if record[3] == 0 else int.valueOf(record[3]) if isinstance(record[3], str) else record[3]
        bean.approval_record = 0 if record[4] == 0 else int.valueOf(record[4]) if isinstance(record[4], str) else record[4]
        bean.score = 0 if record[5] == 0 else int.valueOf(record[5]) if isinstance(record[5], str) else record[5]
        bean.approval_method = 0 if record[6] == 0 else int.valueOf(record[6]) if isinstance(record[6], str) else record[6]
        bean.manager = 0 if record[7] == 0 else int.valueOf(record[7]) if isinstance(record[7], str) else record[7]
        bean.approving = 0 if record[8] == 0 else int.valueOf(record[8]) if isinstance(record[8], str) else record[8]
        bean.signature = record[9]
        bean.path = record[10]
        bean.time = record[11]
        bean.start = record[12]
        bean.end = record[13]
        return bean
        pass

    """Returns a converter from arguments to record
    @return $T"""
    def aArgs2RecordConverter(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateArgsToRecordMethod
        # in file CompilerCommon.java, at line 887
        return lambda approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, start, end:     ["org.openprovenance.templates.fs.FileApproving", approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, start, end]
        pass

    @staticmethod
    def getRelations():
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateGetRelations
        # in file CompilerCommon.java, at line 1484
        table = Map()
        map2 = Map()
        map2 = Map()
        map2.put("--0--", [8, 7, 6])
        table.put("PROV_ASSOCIATION", map2)
        map2 = Map()
        map2.put("der3", [1, 5, 8])
        map2.put("der4", [4, 5, 8])
        map2.put("der1", [1, 3, 8])
        map2.put("der2", [4, 3, 8])
        table.put("PROV_DERIVATION", map2)
        map2 = Map()
        map2.put("--1--", [4, 7])
        map2.put("--0--", [1, 7])
        table.put("PROV_ATTRIBUTION", map2)
        map2 = Map()
        map2.put("--1--", [4, 8])
        map2.put("--0--", [1, 8])
        table.put("PROV_GENERATION", map2)
        map2 = Map()
        map2.put("--1--", [8, 5])
        map2.put("--0--", [8, 3])
        table.put("PROV_USAGE", map2)
        return table
        pass

    @staticmethod
    def getAllTypes():
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateGetAllTypesMethodStatic
        # in file CompilerCommon.java, at line 1839
        table = [None] * (6)
        table[0] = "http://www.w3.org/ns/prov#Entity"
        table[1] = "http://www.w3.org/ns/prov#Activity"
        table[2] = "http://www.w3.org/ns/prov#Agent"
        table[3] = "http://openprovenance.org/ns/fs#ApprovalRecord"
        table[4] = "http://openprovenance.org/ns/fs#ApprovedPipeline"
        table[5] = "http://openprovenance.org/ns/fs#ApprovingPipeline"
        return table
        pass

    """Returns a converter from Processor taking arguments to Processor taking record
    @param __processor a transformer for this template
    @param <T> type variable for the result of processor
    @return $T&lt;$T&gt;"""
    def processorConverter_function(self, processor):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateProcessorConverter
        # in file CompilerCommon.java, at line 918
        return lambda approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, start, end:     processor([getFullyQualifiedName(), approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, start, end])
        pass

    """Null method for composite
    @return null"""
    def getOutputs(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateOutputsMethod
        # in file CompilerCommon.java, at line 1221
        return self.outputs
        pass

    """Null method for composite
    @return null"""
    def getInputs(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateInputsMethod
        # in file CompilerCommon.java, at line 1240
        return self.inputs
        pass

    """Null method for composite
    @return null"""
    def getCompulsoryInputs(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCompulsoryInputsMethod
        # in file CompilerCommon.java, at line 1230
        return self.compulsoryInputs
        pass

    @staticmethod
    def examplar():
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateExamplarBean
        # in file CompilerCommon.java, at line 2079
        bean = File_approvingBean()
        bean.approved_pipeline = int.valueOf("130")
        bean.pipeline = int.valueOf("118")
        bean.approval_record = int.valueOf("9885")
        bean.score = int.valueOf("356")
        bean.approval_method = int.valueOf("222")
        bean.manager = int.valueOf("12345")
        bean.approving = int.valueOf("12345")
        bean.filename = "file/130-approved.pipeline"
        bean.signature = "test2_signature"
        bean.path = "test2_path"
        bean.time = "2026-09-13T12:16:24.737+01:00"
        bean.start = "2026-09-13T12:16:24.737+01:00"
        bean.end = "2026-09-13T12:16:24.737+01:00"
        return bean
        pass

    """Returns a converter from Processor taking arguments to Processor taking record
    @param processor a transformer for this template
    @param <T> type variable for the result of processor
    @return $T&lt;$T&gt;"""
    def processorConverter_file_approving_processor(self, processor):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateProcessorConverter2
        # in file CompilerCommon.java, at line 979
        return lambda record:     processor(0 if record[1] == 0 else int.valueOf(record[1]) if isinstance(record[1], str) else record[1], record[2], 0 if record[3] == 0 else int.valueOf(record[3]) if isinstance(record[3], str) else record[3], 0 if record[4] == 0 else int.valueOf(record[4]) if isinstance(record[4], str) else record[4], 0 if record[5] == 0 else int.valueOf(record[5]) if isinstance(record[5], str) else record[5], 0 if record[6] == 0 else int.valueOf(record[6]) if isinstance(record[6], str) else record[6], 0 if record[7] == 0 else int.valueOf(record[7]) if isinstance(record[7], str) else record[7], 0 if record[8] == 0 else int.valueOf(record[8]) if isinstance(record[8], str) else record[8], record[9], record[10], record[11], record[12], record[13])
        pass

    @staticmethod
    def args2bean(approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, start, end):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateFactoryMethodWithBean
        # in file CompilerCommon.java, at line 1888
        bean = File_approvingBean()
        bean.approved_pipeline = approved_pipeline
        bean.filename = filename
        bean.pipeline = pipeline
        bean.approval_record = approval_record
        bean.score = score
        bean.approval_method = approval_method
        bean.manager = manager
        bean.approving = approving
        bean.signature = signature
        bean.path = path
        bean.time = time
        bean.start = start
        bean.end = end
        return bean
        pass

    """logFile_approving client side logging method
    @return $T"""
    def bean2sql(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateBeanToSqlConversionMethod
        # in file CompilerCommon.java, at line 854
        return lambda approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, start, end:     self.funLambda1(approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, start, end)
        pass

    def sqlTuple(self, sb, approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, start, end):
        # Generated by class org.openprovenance.prov.template.compiler.CompilerSQL, method generateSqlTupleMethod
        # in file CompilerSQL.java, at line 361
        sb.append("(")
        if approved_pipeline == 0:
            sb.append("''")
        else:
            sb.append("")
            sb.append(approved_pipeline)
        sb.append(",")
        if filename == 0:
            sb.append("''")
        else:
            sb.append("'")
            sb.append(filename)
            sb.append("'")
        sb.append(",")
        if pipeline == 0:
            sb.append("''")
        else:
            sb.append("")
            sb.append(pipeline)
        sb.append(",")
        if approval_record == 0:
            sb.append("''")
        else:
            sb.append("")
            sb.append(approval_record)
        sb.append(",")
        if score == 0:
            sb.append("''")
        else:
            sb.append("")
            sb.append(score)
        sb.append(",")
        if approval_method == 0:
            sb.append("''")
        else:
            sb.append("")
            sb.append(approval_method)
        sb.append(",")
        if manager == 0:
            sb.append("''")
        else:
            sb.append("")
            sb.append(manager)
        sb.append(",")
        if approving == 0:
            sb.append("''")
        else:
            sb.append("")
            sb.append(approving)
        sb.append(",")
        if signature == 0:
            sb.append("''")
        else:
            sb.append("'")
            sb.append(signature)
            sb.append("'")
        sb.append(",")
        if path == 0:
            sb.append("''")
        else:
            sb.append("'")
            sb.append(path)
            sb.append("'")
        sb.append(",")
        if time == 0:
            sb.append("''")
        else:
            sb.append("'")
            sb.append(time)
            sb.append("'")
        sb.append(",")
        if start == 0:
            sb.append("''")
        else:
            sb.append("'")
            sb.append(start)
            sb.append("'")
        sb.append(",")
        if end == 0:
            sb.append("''")
        else:
            sb.append("'")
            sb.append(end)
            sb.append("'")
        sb.append(")")
        pass

    def getIntegrator(self):
        # Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateMethodGetIntegrator
        # in file CompilerCommon.java, at line 228
        return self.integrator
        pass

    def funLambda0(self, approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, start, end):
        sb = StringBuilder()
        self.logFile_approving(sb, approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, start, end)
        return sb.toString()
        pass

    def funLambda1(self, approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, start, end):
        sb = StringBuilder()
        self.sqlTuple(sb, approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, start, end)
        return sb.toString()
        pass

    propertyOrder = ["isA", "approved_pipeline", "filename", "pipeline", "approval_record", "score", "approval_method", "manager", "approving", "signature", "path", "time", "start", "end"]
    _sqlInsert1 = "INSERT INTO  file_approving (approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, _start, _end)"
    foreignTables = ["isA", "file", 0, "file", "approval_record", "score", "method", "agent", "activity", 0, 0, 0, 0, 0]
    successors = getSuccessors()
    successors2 = getTypedSuccessors()
    nodes = getNodes()
    relations = getRelations()
    allTypes = getAllTypes()
    outputs = ["approved_pipeline", "approval_record", "approving"]
    inputs = ["filename", "pipeline", "score", "approval_method", "manager", "signature", "path", "time", "start", "end"]
    compulsoryInputs = ["filename", "pipeline", "score"]
    integrator = File_approvingIntegratorBuilder()
