// Generated by ProvToolbox for template configuration 'File_transforming_compositeInputs'
// by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateBean,
// in file CompilerBeanGenerator.java, at line 59

#![allow(dead_code, unused_variables, unused_imports, unused_mut)]

use crate::org::openprovenance::book::fs::client::integrator::file_transforming_inputs_1::FileTransformingInputs1;
use serde::{Serialize, Deserialize};
use crate::org::openprovenance::book::fs::client::integrator::file_transforming_composite_inputs_processor::FileTransformingCompositeInputsProcessor;
use serde_json;

/// A composite bean for file_transforming_composite
///  that only contains the input of this template.
/// 
///  This includes shared variables [transformed_file, transforming].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileTransformingCompositeInputs {
    /// The template name
    #[serde(rename = "isA")]
    pub is_a: String,
    /// bean: The bean identifier (not used for now) (expected type: xsd:string)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bean: Option<String>,
    /// count: The number of records being composed (calculated automatically) (expected type: xsd:int)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// type: The type of bean being composed (expected type: xsd:string)
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "type")]
    pub r#type: Option<String>,
    /// List of composed templates generated Automatically by ProvToolbox (CompilerBeanGenerator.generateCompositeList()) for template org.openprovenance.templates.fs.FileTransforming.
    /// 
    /// Variant _1 for shared variables transformed_file_transforming ([transformed_file, transforming]).
    #[serde(rename = "__elements")]
    pub elements: Vec<FileTransformingInputs1>,
    /// Class of elements inside this composite
    #[serde(rename = "consistsOf")]
    pub consists_of: String,
}

impl FileTransformingCompositeInputs {
    /// Creates a new instance
    pub fn new() -> Self {
        Self {
            is_a: "org.openprovenance.templates.fs.FileTransformingComposite".to_string(),
            bean: None,
            count: None,
            r#type: None,
            elements: Vec::new(),
            consists_of: "org.openprovenance.book.fs.client.integrator.File_transformingInputs_1".to_string(),
        }
    }

    /// Converts to JSON string
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(self)
    }

    pub fn process<T>(&self, processor: impl FileTransformingCompositeInputsProcessor<T> + 'static) -> T {
        // PAST generator method. Created by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateInvokeProcessor
        // in file CompilerBeanGenerator.java, at line 693
        processor.process(self.bean.as_deref().unwrap_or_default(), self.count, self.r#type.as_deref().unwrap_or_default(), &self.elements)
    }

    pub fn share_all_transformed_file(&mut self, v: i32) {
        // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateMutatorForSharedVariables
        // in file CompilerBeanGenerator.java, at line 641
        self.elements.iter_mut().for_each(|b| {
            b.transformed_file = Some(v);
        });
    }

    pub fn distinct_transformed_file(&mut self, v: i32) {
        // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateMutatorForDistinctVariables
        // in file CompilerBeanGenerator.java, at line 614
        let mut count = vec![v];
        self.elements.iter_mut().for_each(|b| {
            b.transformed_file = Some(count[0]);
            count[0] -= 1;
        });
    }

    pub fn share_all_transforming(&mut self, v: i32) {
        // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateMutatorForSharedVariables
        // in file CompilerBeanGenerator.java, at line 641
        self.elements.iter_mut().for_each(|b| {
            b.transforming = Some(v);
        });
    }

    pub fn distinct_transforming(&mut self, v: i32) {
        // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateMutatorForDistinctVariables
        // in file CompilerBeanGenerator.java, at line 614
        let mut count = vec![v];
        self.elements.iter_mut().for_each(|b| {
            b.transforming = Some(count[0]);
            count[0] -= 1;
        });
    }

    pub fn add_elements(&mut self, o: FileTransformingInputs1) {
        // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateCompositeListExtender
        // in file CompilerBeanGenerator.java, at line 668
        self.elements.push(o.clone());
    }

}

