// Generated by ProvToolbox for template configuration 'File_transforming_compositeOutputs'
// by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateBean,
// in file CompilerBeanGenerator.java, at line 59

#![allow(dead_code, unused_variables, unused_imports, unused_mut)]

use serde::{Serialize, Deserialize};
use crate::org::openprovenance::book::fs::client::integrator::file_transforming_outputs::FileTransformingOutputs;
use crate::org::openprovenance::book::fs::client::integrator::file_transforming_composite_outputs_processor::FileTransformingCompositeOutputsProcessor;
use serde_json;

/// A composite bean for file_transforming_composite
///  that only contains the outputs of this template.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileTransformingCompositeOutputs {
    /// The template name
    #[serde(rename = "isA")]
    pub is_a: String,
    /// Allows for database key to be returned.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "ID")]
    pub i_d: Option<i32>,
    /// bean: The bean identifier (not used for now) (expected type: xsd:string)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bean: Option<String>,
    /// count: The number of records being composed (calculated automatically) (expected type: xsd:int)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// type: The type of bean being composed (expected type: xsd:string)
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "type")]
    pub r#type: Option<String>,
    /// List of composed templates generated Automatically by ProvToolbox (CompilerBeanGenerator.generateCompositeList()) for template org.openprovenance.templates.fs.FileTransforming.
    #[serde(rename = "__elements")]
    pub elements: Vec<FileTransformingOutputs>,
    /// Class of elements inside this composite
    #[serde(rename = "consistsOf")]
    pub consists_of: String,
}

impl FileTransformingCompositeOutputs {
    /// Creates a new instance
    pub fn new() -> Self {
        Self {
            is_a: "org.openprovenance.templates.fs.FileTransformingComposite".to_string(),
            i_d: None,
            bean: None,
            count: None,
            r#type: None,
            elements: Vec::new(),
            consists_of: "org.openprovenance.book.fs.client.integrator.File_transformingOutputs".to_string(),
        }
    }

    /// Converts to JSON string
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(self)
    }

    pub fn process<T>(&self, processor: impl FileTransformingCompositeOutputsProcessor<T> + 'static) -> T {
        // PAST generator method. Created by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateInvokeProcessor
        // in file CompilerBeanGenerator.java, at line 693
        processor.process(self.bean.as_deref().unwrap_or_default(), self.count, self.r#type.as_deref().unwrap_or_default(), &self.elements)
    }

    pub fn add_elements(&mut self, o: FileTransformingOutputs) {
        // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateCompositeListExtender
        // in file CompilerBeanGenerator.java, at line 668
        self.elements.push(o.clone());
    }

}

