// Generated by ProvToolbox for template configuration 'File_approvingBuilder'
// by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonLib_aux,
// in file CompilerCommon.java, at line 100

const StringBuilder = past.util.StringBuilder;
const { File_approvingIntegratorBuilder } = require('org/openprovenance/book/fs/client/integrator/File_approvingIntegratorBuilder.js');
const { File_approvingBean } = require('org/openprovenance/book/fs/client/common/File_approvingBean.js');

/**
 * Builder class for file_approving
 */
class File_approvingBuilder {
  constructor(aArgs2CsVConverter = null, aRecord2BeanConverter = null, aRecord2CsvConverter = null, aArgs2BeanConverter = null, aBean2SqlConverter = null, aRecord2SqlConverter = null) {
    this.aArgs2CsVConverter = this.args2csv();
    this.aRecord2BeanConverter = record => this.record2bean(record);
    this.aRecord2CsvConverter = record => this.record2bean(record).process(this.aArgs2CsVConverter);
    this.aArgs2BeanConverter = (__approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end) => this.args2bean(__approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end);
    this.aBean2SqlConverter = this.bean2sql();
    this.aRecord2SqlConverter = record => this.record2bean(record).process(this.aBean2SqlConverter);
  }

  getBaseRelations() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateBaseRelationsAccessor
    // in file CompilerCommon.java, at line 210
    return "[\"file\",\"agent\",\"score\",\"approval_record\",\"activity\",\"method\"]";
  }

  getName() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateNameAccessor
    // in file CompilerCommon.java, at line 377
    return "file_approving";
  }

  getSemanticType() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateGetSemanticTypeField
    // in file CompilerCommon.java, at line 395
    return null;
  }

  getFullyQualifiedName() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateFullyQualifiedNameAccessor
    // in file CompilerCommon.java, at line 409
    return "org.openprovenance.templates.fs.FileApproving";
  }

  getTemplateName() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateTemplateNameAccessor
    // in file CompilerCommon.java, at line 418
    return "org.openprovenance.templates.fs.FileApproving";
  }

  getCBindings() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCBindingsAccessor
    // in file CompilerCommon.java, at line 427
    return "org/openprovenance/cbindings/fs/file-approving.json";
  }

  /**
   * Null method for composite
   * @return the array of properties in order
   */
  getPropertyOrder() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generatePropertyOrderMethod
    // in file CompilerCommon.java, at line 437
    return this.propertyOrder;
  }

  /**
   * Logger method
   * @param sb a StringBuffer
   * @param __approved_pipeline The approved pipeline
   * @param __filename The filename of the approved pipeline
   * @param __pipeline The pipeline before approval
   * @param __approval_record The approval record
   * @param __score The score obtained through validation
   * @param __approval_method The method to transform the file
   * @param __manager The manager approving the ML pipeline
   * @param __approving The activity of approving the pipeline
   * @param __signature The approval's signature
   * @param __path The actual path of the file
   * @param __time Time when the filtered file is created
   * @param __start Time when the transformation starts
   * @param __end Time when the transformation ends
   */
  logFile_approving(sb, __approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end) {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateLoggerMethod
    // in file CompilerCommon.java, at line 1101
    sb.append("org.openprovenance.templates.fs.FileApproving");
    sb.append(",");
    if (__approved_pipeline == null) {
      // empty
    } else {
      sb.append(__approved_pipeline);
    }
    sb.append(",");
    if (__filename == null) {
      // empty
    } else {
      sb.append(__filename);
    }
    sb.append(",");
    if (__pipeline == null) {
      // empty
    } else {
      sb.append(__pipeline);
    }
    sb.append(",");
    if (__approval_record == null) {
      // empty
    } else {
      sb.append(__approval_record);
    }
    sb.append(",");
    if (__score == null) {
      // empty
    } else {
      sb.append(__score);
    }
    sb.append(",");
    if (__approval_method == null) {
      // empty
    } else {
      sb.append(__approval_method);
    }
    sb.append(",");
    if (__manager == null) {
      // empty
    } else {
      sb.append(__manager);
    }
    sb.append(",");
    if (__approving == null) {
      // empty
    } else {
      sb.append(__approving);
    }
    sb.append(",");
    if (__signature == null) {
      // empty
    } else {
      sb.append(__signature);
    }
    sb.append(",");
    if (__path == null) {
      // empty
    } else {
      sb.append(__path);
    }
    sb.append(",");
    if (__time == null) {
      // empty
    } else {
      sb.append(__time);
    }
    sb.append(",");
    if (__start == null) {
      // empty
    } else {
      sb.append(__start);
    }
    sb.append(",");
    if (__end == null) {
      // empty
    } else {
      sb.append(__end);
    }
  }

  /**
   * logFile_approving client side logging method
   * @return $T
   */
  args2csv() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonCSVConverterMethod
    // in file CompilerCommon.java, at line 480
    let self = this;
    return this.lambda0.bind(this);
  }

  getNodes() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonMethodGetNodes2
    // in file CompilerCommon.java, at line 1202
    return this.__nodes;
  }

  getSuccessors() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonMethodGetSuccessors
    // in file CompilerCommon.java, at line 1281
    return this.__successors;
  }

  getTypedSuccessors() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonMethodGetTypedSuccessors
    // in file CompilerCommon.java, at line 1308
    return this.__successors2;
  }

  newBean() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateNewBean
    // in file CompilerCommon.java, at line 2064
    let bean = new File_approvingBean();
    return bean;
  }

  record2csv(record) {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateRecordCsvProcessorMethod
    // in file CompilerCommon.java, at line 1269
    return aRecord2CsvConverter;
  }

  isCompositeOf() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateIsCompositeOfMethod
    // in file CompilerCommon.java, at line 363
    return null;
  }

  getSQLInsert() {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerSQL, method generateSQLInsert
    // in file CompilerSQL.java, at line 259
    return this._sqlInsert1;
  }

  getSQLInsertStatement() {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerSQL, method generateSQLInsertStatement
    // in file CompilerSQL.java, at line 272
    return "_sqlInsert1 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
  }

  getForeign() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonMethodGetForeign
    // in file CompilerCommon.java, at line 1295
    return foreignTables;
  }

  static __getSuccessors() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonMethod4static
    // in file CompilerCommon.java, at line 1324
    let table = new Map();
    table.put(1, []);
    table.put(3, [4, 1]);
    table.put(4, []);
    table.put(5, [4, 1]);
    table.put(6, []);
    table.put(7, []);
    table.put(8, []);
    return table;
  }

  /**
   * Apply method
   * @param processor a transformer for this template
   * @param record as an array of Objects
   * @param <T> type variable for the result of processor
   * @return an object of type $T
   */
  apply(processor, record) {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateApplyMethod
    // in file CompilerCommon.java, at line 1043
    return this.record2bean(record)(processor);
  }

  static __getNodes() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateGetNodeStatic
    // in file CompilerCommon.java, at line 1181
    return [1, 3, 4, 5, 6, 7, 8];
  }

  static __getTypedSuccessors() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateGetTypedSuccessorsStatic
    // in file CompilerCommon.java, at line 1722
    let table = new Map();
    table.put(1, []);
    table.put(3, [4, 9, 1, 9]);
    table.put(4, []);
    table.put(5, [4, 9, 1, 9]);
    table.put(6, []);
    table.put(7, [1, 11, 4, 11]);
    table.put(8, []);
    return table;
  }

  /**
   * Converter to bean of type $T for template ClassName{packge='org.openprovenance.book.fs.client.common', simpleName='File_approvingBean'}.
   * @param record an array of objects
   * @return a bean
   */
  record2bean(record) {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateFactoryMethodToBeanWithArray
    // in file CompilerCommon.java, at line 2007
    let bean = new File_approvingBean();
    bean.approved_pipeline = record[1] == null ? null : record[1] instanceof String ? Number.valueOf(record[1]) : record[1];
    bean.filename = record[2];
    bean.pipeline = record[3] == null ? null : record[3] instanceof String ? Number.valueOf(record[3]) : record[3];
    bean.approval_record = record[4] == null ? null : record[4] instanceof String ? Number.valueOf(record[4]) : record[4];
    bean.score = record[5] == null ? null : record[5] instanceof String ? Number.valueOf(record[5]) : record[5];
    bean.approval_method = record[6] == null ? null : record[6] instanceof String ? Number.valueOf(record[6]) : record[6];
    bean.manager = record[7] == null ? null : record[7] instanceof String ? Number.valueOf(record[7]) : record[7];
    bean.approving = record[8] == null ? null : record[8] instanceof String ? Number.valueOf(record[8]) : record[8];
    bean.signature = record[9];
    bean.path = record[10];
    bean.time = record[11];
    bean.start = record[12];
    bean.end = record[13];
    return bean;
  }

  /**
   * Returns a converter from arguments to record
   * @return $T
   */
  aArgs2RecordConverter() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateArgsToRecordMethod
    // in file CompilerCommon.java, at line 887
    return (__approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end) => ["org.openprovenance.templates.fs.FileApproving", __approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end];
  }

  static __getRelations() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateGetRelations
    // in file CompilerCommon.java, at line 1484
    let table = new Map();
    let map2 = new Map();
    map2 = new Map();
    map2.put("--0--", [8, 7, 6]);
    table.put("PROV_ASSOCIATION", map2);
    map2 = new Map();
    map2.put("der3", [1, 5, 8]);
    map2.put("der4", [4, 5, 8]);
    map2.put("der1", [1, 3, 8]);
    map2.put("der2", [4, 3, 8]);
    table.put("PROV_DERIVATION", map2);
    map2 = new Map();
    map2.put("--1--", [4, 7]);
    map2.put("--0--", [1, 7]);
    table.put("PROV_ATTRIBUTION", map2);
    map2 = new Map();
    map2.put("--1--", [4, 8]);
    map2.put("--0--", [1, 8]);
    table.put("PROV_GENERATION", map2);
    map2 = new Map();
    map2.put("--1--", [8, 5]);
    map2.put("--0--", [8, 3]);
    table.put("PROV_USAGE", map2);
    return table;
  }

  static __getAllTypes() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateGetAllTypesMethodStatic
    // in file CompilerCommon.java, at line 1839
    let table = new Array(6);
    table[0] = "http://www.w3.org/ns/prov#Entity";
    table[1] = "http://www.w3.org/ns/prov#Activity";
    table[2] = "http://www.w3.org/ns/prov#Agent";
    table[3] = "http://openprovenance.org/ns/fs#ApprovalRecord";
    table[4] = "http://openprovenance.org/ns/fs#ApprovedPipeline";
    table[5] = "http://openprovenance.org/ns/fs#ApprovingPipeline";
    return table;
  }

  /**
   * Returns a converter from Processor taking arguments to Processor taking record
   * @param __processor a transformer for this template
   * @param <T> type variable for the result of processor
   * @return $T&lt;$T&gt;
   */
  processorConverter_function(__processor) {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateProcessorConverter
    // in file CompilerCommon.java, at line 918
    return (__approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end) => __processor([getFullyQualifiedName(), __approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end]);
  }

  /**
   * Null method for composite
   * @return null
   */
  getOutputs() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateOutputsMethod
    // in file CompilerCommon.java, at line 1221
    return this.outputs;
  }

  /**
   * Null method for composite
   * @return null
   */
  getInputs() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateInputsMethod
    // in file CompilerCommon.java, at line 1240
    return this.inputs;
  }

  /**
   * Null method for composite
   * @return null
   */
  getCompulsoryInputs() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCompulsoryInputsMethod
    // in file CompilerCommon.java, at line 1230
    return this.compulsoryInputs;
  }

  static examplar() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateExamplarBean
    // in file CompilerCommon.java, at line 2079
    let bean = new File_approvingBean();
    bean.approved_pipeline = Number.valueOf("130");
    bean.pipeline = Number.valueOf("118");
    bean.approval_record = Number.valueOf("9885");
    bean.score = Number.valueOf("356");
    bean.approval_method = Number.valueOf("222");
    bean.manager = Number.valueOf("12345");
    bean.approving = Number.valueOf("12345");
    bean.filename = "file/130-approved.pipeline";
    bean.signature = "test2_signature";
    bean.path = "test2_path";
    bean.time = "2026-09-13T12:16:24.737+01:00";
    bean.start = "2026-09-13T12:16:24.737+01:00";
    bean.end = "2026-09-13T12:16:24.737+01:00";
    return bean;
  }

  /**
   * Returns a converter from Processor taking arguments to Processor taking record
   * @param processor a transformer for this template
   * @param <T> type variable for the result of processor
   * @return $T&lt;$T&gt;
   */
  processorConverter_file_approving_processor(processor) {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateProcessorConverter2
    // in file CompilerCommon.java, at line 979
    return record => processor(record[1] == null ? null : record[1] instanceof String ? Number.valueOf(record[1]) : record[1], record[2], record[3] == null ? null : record[3] instanceof String ? Number.valueOf(record[3]) : record[3], record[4] == null ? null : record[4] instanceof String ? Number.valueOf(record[4]) : record[4], record[5] == null ? null : record[5] instanceof String ? Number.valueOf(record[5]) : record[5], record[6] == null ? null : record[6] instanceof String ? Number.valueOf(record[6]) : record[6], record[7] == null ? null : record[7] instanceof String ? Number.valueOf(record[7]) : record[7], record[8] == null ? null : record[8] instanceof String ? Number.valueOf(record[8]) : record[8], record[9], record[10], record[11], record[12], record[13]);
  }

  static args2bean(__approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end) {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateFactoryMethodWithBean
    // in file CompilerCommon.java, at line 1888
    let bean = new File_approvingBean();
    bean.approved_pipeline = __approved_pipeline;
    bean.filename = __filename;
    bean.pipeline = __pipeline;
    bean.approval_record = __approval_record;
    bean.score = __score;
    bean.approval_method = __approval_method;
    bean.manager = __manager;
    bean.approving = __approving;
    bean.signature = __signature;
    bean.path = __path;
    bean.time = __time;
    bean.start = __start;
    bean.end = __end;
    return bean;
  }

  /**
   * logFile_approving client side logging method
   * @return $T
   */
  bean2sql() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateBeanToSqlConversionMethod
    // in file CompilerCommon.java, at line 854
    let self = this;
    return this.lambda1.bind(this);
  }

  sqlTuple(sb, __approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end) {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerSQL, method generateSqlTupleMethod
    // in file CompilerSQL.java, at line 361
    sb.append("(");
    if (__approved_pipeline == null) {
      sb.append("''");
    } else {
      sb.append("");
      sb.append(__approved_pipeline);
    }
    sb.append(",");
    if (__filename == null) {
      sb.append("''");
    } else {
      sb.append("'");
      sb.append(__filename);
      sb.append("'");
    }
    sb.append(",");
    if (__pipeline == null) {
      sb.append("''");
    } else {
      sb.append("");
      sb.append(__pipeline);
    }
    sb.append(",");
    if (__approval_record == null) {
      sb.append("''");
    } else {
      sb.append("");
      sb.append(__approval_record);
    }
    sb.append(",");
    if (__score == null) {
      sb.append("''");
    } else {
      sb.append("");
      sb.append(__score);
    }
    sb.append(",");
    if (__approval_method == null) {
      sb.append("''");
    } else {
      sb.append("");
      sb.append(__approval_method);
    }
    sb.append(",");
    if (__manager == null) {
      sb.append("''");
    } else {
      sb.append("");
      sb.append(__manager);
    }
    sb.append(",");
    if (__approving == null) {
      sb.append("''");
    } else {
      sb.append("");
      sb.append(__approving);
    }
    sb.append(",");
    if (__signature == null) {
      sb.append("''");
    } else {
      sb.append("'");
      sb.append(__signature);
      sb.append("'");
    }
    sb.append(",");
    if (__path == null) {
      sb.append("''");
    } else {
      sb.append("'");
      sb.append(__path);
      sb.append("'");
    }
    sb.append(",");
    if (__time == null) {
      sb.append("''");
    } else {
      sb.append("'");
      sb.append(__time);
      sb.append("'");
    }
    sb.append(",");
    if (__start == null) {
      sb.append("''");
    } else {
      sb.append("'");
      sb.append(__start);
      sb.append("'");
    }
    sb.append(",");
    if (__end == null) {
      sb.append("''");
    } else {
      sb.append("'");
      sb.append(__end);
      sb.append("'");
    }
    sb.append(")");
  }

  getIntegrator() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateMethodGetIntegrator
    // in file CompilerCommon.java, at line 228
    return this.__integrator;
  }

  lambda0(__approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end) {
    let sb = new StringBuilder();
    self.logFile_approving(sb, __approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end);
    return sb.toString();
  }

  lambda1(__approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end) {
    let sb = new StringBuilder();
    self.sqlTuple(sb, __approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end);
    return sb.toString();
  }


static propertyOrder = ["isA", "approved_pipeline", "filename", "pipeline", "approval_record", "score", "approval_method", "manager", "approving", "signature", "path", "time", "start", "end"];

static _sqlInsert1 = "INSERT INTO  file_approving (approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, _start, _end)";

static foreignTables = ["isA", "file", null, "file", "approval_record", "score", "method", "agent", "activity", null, null, null, null, null];

static __successors = File_approvingBuilder.__getSuccessors();

static __successors2 = File_approvingBuilder.__getTypedSuccessors();

static __nodes = File_approvingBuilder.__getNodes();

static __relations = File_approvingBuilder.__getRelations();

static allTypes = File_approvingBuilder.__getAllTypes();

static outputs = ["approved_pipeline", "approval_record", "approving"];

static inputs = ["filename", "pipeline", "score", "approval_method", "manager", "signature", "path", "time", "start", "end"];

static compulsoryInputs = ["filename", "pipeline", "score"];

static __integrator = new File_approvingIntegratorBuilder();
}

module.exports = { File_approvingBuilder,  };
