// Generated by ProvToolbox for template configuration 'File_transforming_compositeInputs'
// by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateBean,
// in file CompilerBeanGenerator.java, at line 59

/**
 * A composite bean for file_transforming_composite
 *  that only contains the input of this template.
 * 
 *  This includes shared variables [transformed_file, transforming].
 */
class File_transforming_compositeInputs {
  constructor(isA = null, bean = null, count = null, type = null, __elements = null, consistsOf = null) {
    this.isA = "org.openprovenance.templates.fs.FileTransformingComposite";
    this.bean = bean;
    this.count = count;
    this.type = type;
    this.__elements = [];
    this.consistsOf = "org.openprovenance.book.fs.client.integrator.File_transformingInputs_1";
  }

  process(__processor) {
    // PAST generator method. Created by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateInvokeProcessor
    // in file CompilerBeanGenerator.java, at line 693
    return __processor(this.bean, this.count, this.type, this.__elements);
  }

  shareAllTransformed_file(v) {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateMutatorForSharedVariables
    // in file CompilerBeanGenerator.java, at line 641
    this.__elements.forEach(b => {
      b.transformed_file = v;
    });
  }

  distinctTransformed_file(v) {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateMutatorForDistinctVariables
    // in file CompilerBeanGenerator.java, at line 614
    const __count = [v];
    this.__elements.forEach(b => {
      b.transformed_file = __count[0];
      __count[0]--;
    });
  }

  shareAllTransforming(v) {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateMutatorForSharedVariables
    // in file CompilerBeanGenerator.java, at line 641
    this.__elements.forEach(b => {
      b.transforming = v;
    });
  }

  distinctTransforming(v) {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateMutatorForDistinctVariables
    // in file CompilerBeanGenerator.java, at line 614
    const __count = [v];
    this.__elements.forEach(b => {
      b.transforming = __count[0];
      __count[0]--;
    });
  }

  addElements(o) {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateCompositeListExtender
    // in file CompilerBeanGenerator.java, at line 668
    this.__elements.push(o);
  }

}

module.exports = { File_transforming_compositeInputs,  };
