// Generated automatically by ProvToolbox for template configuration 'fs_template_library'
// by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateBean,
// in file CompilerBeanGenerator.java, at line 59
package org.openprovenance.book.fs.client.integrator;

import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.LinkedList;
import java.util.List;

/**
 * A composite bean for file_transforming_composite that only contains the input of this template.
 *  This includes shared variables [transformed_file, transforming].
 */
public class File_transforming_compositeInputs {
  /**
   * The template name
   */
  public final String isA = "org.openprovenance.templates.fs.FileTransformingComposite";

  /**
   * bean: The bean identifier (not used for now) (expected type: xsd:string)
   */
  public String bean;

  /**
   * count: The number of records being composed (calculated automatically) (expected type: xsd:int)
   */
  public Integer count;

  /**
   * type: The type of bean being composed (expected type: xsd:string)
   */
  public String type;

  /**
   * List of composed templates generated Automatically by ProvToolbox (CompilerBeanGenerator.generateCompositeList()) for template org.openprovenance.templates.fs.FileTransforming.
   * Variant _1 for shared variables transformed_file_transforming ([transformed_file, transforming]).
   */
  public List<File_transformingInputs_1> __elements = new LinkedList<>();

  /**
   * Class of elements inside this composite
   */
  public String consistsOf = "org.openprovenance.book.fs.client.integrator.File_transformingInputs_1";

  public <T> T process(File_transforming_compositeInputsProcessor<T> __processor) {
    // PAST generator method. Created by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateInvokeProcessor;
    // in file CompilerBeanGenerator.java, at line 693;
    return __processor.process(bean,count,type,__elements);
  }

  public void shareAllTransformed_file(Integer v) {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateMutatorForSharedVariables;
    // in file CompilerBeanGenerator.java, at line 641;
    __elements.forEach(b -> {
          b.transformed_file=v;
        });
  }

  public void distinctTransformed_file(Integer v) {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateMutatorForDistinctVariables;
    // in file CompilerBeanGenerator.java, at line 614;
    final int[] __count=new int[] { v };
    __elements.forEach(b -> {
          b.transformed_file=__count[0]--;
        });
  }

  public void shareAllTransforming(Integer v) {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateMutatorForSharedVariables;
    // in file CompilerBeanGenerator.java, at line 641;
    __elements.forEach(b -> {
          b.transforming=v;
        });
  }

  public void distinctTransforming(Integer v) {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateMutatorForDistinctVariables;
    // in file CompilerBeanGenerator.java, at line 614;
    final int[] __count=new int[] { v };
    __elements.forEach(b -> {
          b.transforming=__count[0]--;
        });
  }

  public void addElements(Object o) {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateCompositeListExtender;
    // in file CompilerBeanGenerator.java, at line 668;
    __elements.add((File_transformingInputs_1)o);
  }
}
