// Generated by ProvToolbox for template configuration 'File_transforming_compositeOutputs'
// by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateBean,
// in file CompilerBeanGenerator.java, at line 59

/**
 * A composite bean for file_transforming_composite
 *  that only contains the outputs of this template.
 */
class File_transforming_compositeOutputs {
  constructor(isA = null, ID = null, bean = null, count = null, type = null, __elements = null, consistsOf = null) {
    this.isA = "org.openprovenance.templates.fs.FileTransformingComposite";
    this.ID = ID;
    this.bean = bean;
    this.count = count;
    this.type = type;
    this.__elements = [];
    this.consistsOf = "org.openprovenance.book.fs.client.integrator.File_transformingOutputs";
  }

  process(__processor) {
    // PAST generator method. Created by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateInvokeProcessor
    // in file CompilerBeanGenerator.java, at line 693
    return __processor(this.bean, this.count, this.type, this.__elements);
  }

  addElements(o) {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateCompositeListExtender
    // in file CompilerBeanGenerator.java, at line 668
    this.__elements.push(o);
  }

}

module.exports = { File_transforming_compositeOutputs,  };
