# Generated by ProvToolbox for template configuration 'File_transforming_compositeInputs'
# by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateBean,
# in file CompilerBeanGenerator.java, at line 59

from past.util.Map import Map
from past.util.List import List


"""A composite bean for file_transforming_composite
 that only contains the input of this template.

 This includes shared variables [transformed_file, transforming]."""
class File_transforming_compositeInputs:
    def __init__(self, bean=None, count=None, type=None, elements=None, consistsOf=None):
        self.isA = "org.openprovenance.templates.fs.FileTransformingComposite"
        self.bean = bean
        self.count = count
        self.type = type
        self.elements = List()
        self.consistsOf = "org.openprovenance.book.fs.client.integrator.File_transformingInputs_1"

    def toJSON(self):
        import json
        d = {('__elements' if k == 'elements' else k): v
            for k, v in self.__dict__.items()}
        return json.dumps(
            d,
            default=lambda o: o.__dict__,
            sort_keys=False,
            indent=4)

    def process(self, processor):
        # PAST generator method. Created by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateInvokeProcessor
        # in file CompilerBeanGenerator.java, at line 693
        return processor(self.bean, self.count, self.type, self.elements)
        pass

    def shareAllTransformed_file(self, v):
        # Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateMutatorForSharedVariables
        # in file CompilerBeanGenerator.java, at line 641
        for b in self.elements:
            b.transformed_file = v

        pass

    def distinctTransformed_file(self, v):
        # Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateMutatorForDistinctVariables
        # in file CompilerBeanGenerator.java, at line 614
        count = [v]
        for b in self.elements:
            b.transformed_file = count[0]
            count[0] -= 1


        pass

    def shareAllTransforming(self, v):
        # Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateMutatorForSharedVariables
        # in file CompilerBeanGenerator.java, at line 641
        for b in self.elements:
            b.transforming = v

        pass

    def distinctTransforming(self, v):
        # Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateMutatorForDistinctVariables
        # in file CompilerBeanGenerator.java, at line 614
        count = [v]
        for b in self.elements:
            b.transforming = count[0]
            count[0] -= 1


        pass

    def addElements(self, o):
        # Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateCompositeListExtender
        # in file CompilerBeanGenerator.java, at line 668
        self.elements.append(o)
        pass

    bean = None
    count = None
    type = None
