// Generated automatically by ProvToolbox for template configuration 'fs_template_library'
// by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonLib_aux,
// in file CompilerCommon.java, at line 100
package org.openprovenance.book.fs.client.common;

import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;
import org.openprovenance.book.fs.client.integrator.File_approvingIntegratorBuilder;
import org.openprovenance.prov.client.Builder;
import org.openprovenance.prov.client.SQL;

/**
 * Builder class for file_approving
 */
public class File_approvingBuilder implements Builder, SQL {
  /**
   * Generated by method org.openprovenance.prov.template.compiler.common.CompilerCommon.generateFieldPropertyOrder()
   */
  public static final String[] propertyOrder = new String[] { "isA","approved_pipeline","filename","pipeline","approval_record","score","approval_method","manager","approving","signature","path","time","start","end" };

  private static String _sqlInsert1 = "INSERT INTO  file_approving (approved_pipeline, filename, pipeline, approval_record, score, approval_method, manager, approving, signature, path, time, _start, _end)";

  /**
   * Generated by method org.openprovenance.prov.template.compiler.common.CompilerCommon.generateFieldForeignTables()
   */
  public static final String[] foreignTables = new String[] { "isA","file",null,"file","approval_record","score","method","agent","activity",null,null,null,null,null };

  /**
   * Generated by method org.openprovenance.prov.template.compiler.common.CompilerCommon.generateStaticFieldSuccessor()
   */
  public static final Map<Integer, int[]> __successors = __getSuccessors();

  /**
   * Generated by method org.openprovenance.prov.template.compiler.common.CompilerCommon.generateStaticFieldSuccessor2()
   */
  public static final Map<Integer, int[]> __successors2 = __getTypedSuccessors();

  /**
   * Generated by method org.openprovenance.prov.template.compiler.common.CompilerCommon.generateStaticFieldNodes()
   */
  public static final int[] __nodes = __getNodes();

  /**
   * Generated by method org.openprovenance.prov.template.compiler.common.CompilerCommon.generateStaticFieldRelations()
   */
  public static final Map<String, Map<String, int[]>> __relations = __getRelations();

  /**
   * Generated by method org.openprovenance.prov.template.compiler.common.CompilerCommon.generateStaticFieldAllTypes()
   */
  public static final String[] allTypes = __getAllTypes();

  public static final String[] outputs = new String[] { "approved_pipeline","approval_record","approving" };

  public static final String[] inputs = new String[] { "filename","pipeline","score","approval_method","manager","signature","path","time","start","end" };

  public static final String[] compulsoryInputs = new String[] { "filename","pipeline","score" };

  /**
   * Generated by method org.openprovenance.prov.template.compiler.common.CompilerCommon.generateStaticFieldIntegrator()
   */
  public static final File_approvingIntegratorBuilder __integrator = new File_approvingIntegratorBuilder();

  /**
   * Generated by method org.openprovenance.prov.template.compiler.common.CompilerCommon.generateField4aArgs2CsvConverter()
   */
  public final File_approvingProcessor<String> aArgs2CsVConverter = this.args2csv();

  /**
   * Generated by method org.openprovenance.prov.template.compiler.common.CompilerCommon.generateField4aBeanConverter2()
   */
  public final Function<Object[], File_approvingBean> aRecord2BeanConverter = record -> {
    return this.record2bean(record);
  };

  /**
   * Generated by method org.openprovenance.prov.template.compiler.common.CompilerCommon.generateFieldRecord2CsvConverter()
   */
  public final Function<Object[], String> aRecord2CsvConverter = record -> {
    return this.record2bean(record).process(aArgs2CsVConverter);
  };

  /**
   * Generated by method org.openprovenance.prov.template.compiler.common.CompilerCommon.generateField4aBeanConverter()
   */
  public final File_approvingProcessor<File_approvingBean> aArgs2BeanConverter = (__approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end) -> {
    return args2bean(__approved_pipeline,__filename,__pipeline,__approval_record,__score,__approval_method,__manager,__approving,__signature,__path,__time,__start,__end);
  };

  /**
   * Generated by method org.openprovenance.prov.template.compiler.common.CompilerCommon.generateFieldBeanConverter()
   */
  public final File_approvingProcessor<String> aBean2SqlConverter = this.bean2sql();

  /**
   * Generated by method org.openprovenance.prov.template.compiler.common.CompilerCommon.generateField4aRecord2SqlConverter()
   */
  public final Function<Object[], String> aRecord2SqlConverter = record -> {
    return this.record2bean(record).process(aBean2SqlConverter);
  };

  public final String getBaseRelations() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateBaseRelationsAccessor;
    // in file CompilerCommon.java, at line 210;
    return "[\"file\",\"agent\",\"score\",\"approval_record\",\"activity\",\"method\"]";
  }

  public String getName() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateNameAccessor;
    // in file CompilerCommon.java, at line 377;
    return "file_approving";
  }

  public String getSemanticType() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateGetSemanticTypeField;
    // in file CompilerCommon.java, at line 395;
    return null;
  }

  public String getFullyQualifiedName() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateFullyQualifiedNameAccessor;
    // in file CompilerCommon.java, at line 409;
    return "org.openprovenance.templates.fs.FileApproving";
  }

  public String getTemplateName() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateTemplateNameAccessor;
    // in file CompilerCommon.java, at line 418;
    return "org.openprovenance.templates.fs.FileApproving";
  }

  public String getCBindings() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCBindingsAccessor;
    // in file CompilerCommon.java, at line 427;
    return "org/openprovenance/cbindings/fs/file-approving.json";
  }

  /**
   * Null method for composite
   * @return the array of properties in order
   */
  public String[] getPropertyOrder() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generatePropertyOrderMethod;
    // in file CompilerCommon.java, at line 437;
    return propertyOrder;
  }

  /**
   * Logger method
   * @param sb a StringBuffer
   * @param __approved_pipeline The approved pipeline
   * @param __filename The filename of the approved pipeline
   * @param __pipeline The pipeline before approval
   * @param __approval_record The approval record
   * @param __score The score obtained through validation
   * @param __approval_method The method to transform the file
   * @param __manager The manager approving the ML pipeline
   * @param __approving The activity of approving the pipeline
   * @param __signature The approval's signature
   * @param __path The actual path of the file
   * @param __time Time when the filtered file is created
   * @param __start Time when the transformation starts
   * @param __end Time when the transformation ends
   */
  public void logFile_approving(StringBuilder sb, Integer __approved_pipeline, String __filename,
      Integer __pipeline, Integer __approval_record, Integer __score, Integer __approval_method,
      Integer __manager, Integer __approving, String __signature, String __path, String __time,
      String __start, String __end) {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateLoggerMethod;
    // in file CompilerCommon.java, at line 1101;
    sb.append("org.openprovenance.templates.fs.FileApproving");
    sb.append(",");
    if ((__approved_pipeline == null)) {
    } else {
      sb.append(__approved_pipeline);
    }
    sb.append(",");
    if ((__filename == null)) {
    } else {
      sb.append(__filename);
    }
    sb.append(",");
    if ((__pipeline == null)) {
    } else {
      sb.append(__pipeline);
    }
    sb.append(",");
    if ((__approval_record == null)) {
    } else {
      sb.append(__approval_record);
    }
    sb.append(",");
    if ((__score == null)) {
    } else {
      sb.append(__score);
    }
    sb.append(",");
    if ((__approval_method == null)) {
    } else {
      sb.append(__approval_method);
    }
    sb.append(",");
    if ((__manager == null)) {
    } else {
      sb.append(__manager);
    }
    sb.append(",");
    if ((__approving == null)) {
    } else {
      sb.append(__approving);
    }
    sb.append(",");
    if ((__signature == null)) {
    } else {
      sb.append(__signature);
    }
    sb.append(",");
    if ((__path == null)) {
    } else {
      sb.append(__path);
    }
    sb.append(",");
    if ((__time == null)) {
    } else {
      sb.append(__time);
    }
    sb.append(",");
    if ((__start == null)) {
    } else {
      sb.append(__start);
    }
    sb.append(",");
    if ((__end == null)) {
    } else {
      sb.append(__end);
    }
  }

  /**
   * logFile_approving client side logging method
   * @return File_approvingProcessor
   */
  public File_approvingProcessor<String> args2csv() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonCSVConverterMethod;
    // in file CompilerCommon.java, at line 480;
    File_approvingBuilder self=this;
    return (__approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end) -> {
          StringBuilder sb=new StringBuilder();
          self.logFile_approving(sb,__approved_pipeline,__filename,__pipeline,__approval_record,__score,__approval_method,__manager,__approving,__signature,__path,__time,__start,__end);
          return sb.toString();
        };
  }

  public int[] getNodes() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonMethodGetNodes2;
    // in file CompilerCommon.java, at line 1202;
    return __nodes;
  }

  public Map<Integer, int[]> getSuccessors() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonMethodGetSuccessors;
    // in file CompilerCommon.java, at line 1281;
    return __successors;
  }

  public Map<Integer, int[]> getTypedSuccessors() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonMethodGetTypedSuccessors;
    // in file CompilerCommon.java, at line 1308;
    return __successors2;
  }

  public File_approvingBean newBean() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateNewBean;
    // in file CompilerCommon.java, at line 2064;
    File_approvingBean bean=new File_approvingBean();
    return bean;
  }

  public Function<Object[], String> record2csv(Object[] record) {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateRecordCsvProcessorMethod;
    // in file CompilerCommon.java, at line 1269;
    return aRecord2CsvConverter;
  }

  public String isCompositeOf() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateIsCompositeOfMethod;
    // in file CompilerCommon.java, at line 363;
    return null;
  }

  public String getSQLInsert() {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerSQL, method generateSQLInsert;
    // in file CompilerSQL.java, at line 259;
    return _sqlInsert1;
  }

  public String getSQLInsertStatement() {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerSQL, method generateSQLInsertStatement;
    // in file CompilerSQL.java, at line 272;
    return "_sqlInsert1 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
  }

  public String[] getForeign() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonMethodGetForeign;
    // in file CompilerCommon.java, at line 1295;
    return foreignTables;
  }

  public static Map<Integer, int[]> __getSuccessors() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCommonMethod4static;
    // in file CompilerCommon.java, at line 1324;
    Map<Integer, int[]> table=new HashMap<Integer, int[]>();
    table.put(1,new int[] {  });
    table.put(3,new int[] { 4,1 });
    table.put(4,new int[] {  });
    table.put(5,new int[] { 4,1 });
    table.put(6,new int[] {  });
    table.put(7,new int[] {  });
    table.put(8,new int[] {  });
    return table;
  }

  /**
   * Apply method
   * @param processor a transformer for this template
   * @param record as an array of Objects
   * @param <T> type variable for the result of processor
   * @return an object of type T
   */
  public <T> T apply(File_approvingProcessor<T> processor, Object[] record) {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateApplyMethod;
    // in file CompilerCommon.java, at line 1043;
    return this.record2bean(record).process(processor);
  }

  public static int[] __getNodes() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateGetNodeStatic;
    // in file CompilerCommon.java, at line 1181;
    return new int[] { 1,3,4,5,6,7,8 };
  }

  public static Map<Integer, int[]> __getTypedSuccessors() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateGetTypedSuccessorsStatic;
    // in file CompilerCommon.java, at line 1722;
    Map<Integer, int[]> table=new HashMap<Integer, int[]>();
    table.put(1,new int[] {  });
    table.put(3,new int[] { 4,9,1,9 });
    table.put(4,new int[] {  });
    table.put(5,new int[] { 4,9,1,9 });
    table.put(6,new int[] {  });
    table.put(7,new int[] { 1,11,4,11 });
    table.put(8,new int[] {  });
    return table;
  }

  /**
   * Converter to bean of type File_approvingBean for template file_approving.
   * @param record an array of objects
   * @return a bean
   */
  public File_approvingBean record2bean(Object[] record) {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateFactoryMethodToBeanWithArray;
    // in file CompilerCommon.java, at line 2007;
    File_approvingBean bean=new File_approvingBean();
    bean.approved_pipeline=((record[1] == null) ? null : ((record[1] instanceof String) ? Integer.valueOf((String)record[1]) : (Integer)record[1]));
    bean.filename=(String)record[2];
    bean.pipeline=((record[3] == null) ? null : ((record[3] instanceof String) ? Integer.valueOf((String)record[3]) : (Integer)record[3]));
    bean.approval_record=((record[4] == null) ? null : ((record[4] instanceof String) ? Integer.valueOf((String)record[4]) : (Integer)record[4]));
    bean.score=((record[5] == null) ? null : ((record[5] instanceof String) ? Integer.valueOf((String)record[5]) : (Integer)record[5]));
    bean.approval_method=((record[6] == null) ? null : ((record[6] instanceof String) ? Integer.valueOf((String)record[6]) : (Integer)record[6]));
    bean.manager=((record[7] == null) ? null : ((record[7] instanceof String) ? Integer.valueOf((String)record[7]) : (Integer)record[7]));
    bean.approving=((record[8] == null) ? null : ((record[8] instanceof String) ? Integer.valueOf((String)record[8]) : (Integer)record[8]));
    bean.signature=(String)record[9];
    bean.path=(String)record[10];
    bean.time=(String)record[11];
    bean.start=(String)record[12];
    bean.end=(String)record[13];
    return bean;
  }

  /**
   * Returns a converter from arguments to record
   * @return File_approvingProcessor
   */
  public File_approvingProcessor<Object[]> aArgs2RecordConverter() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateArgsToRecordMethod;
    // in file CompilerCommon.java, at line 887;
    return (__approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end) -> {
          return new Object[] { "org.openprovenance.templates.fs.FileApproving",__approved_pipeline,__filename,__pipeline,__approval_record,__score,__approval_method,__manager,__approving,__signature,__path,__time,__start,__end };
        };
  }

  public static Map<String, Map<String, int[]>> __getRelations() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateGetRelations;
    // in file CompilerCommon.java, at line 1484;
    Map<String, Map<String, int[]>> table=new HashMap<String, Map<String, int[]>>();
    Map<String, int[]> map2=new HashMap<String, int[]>();
    map2=new HashMap<String, int[]>();
    map2.put("--0--",new int[] { 8,7,6 });
    table.put("PROV_ASSOCIATION",map2);
    map2=new HashMap<String, int[]>();
    map2.put("der3",new int[] { 1,5,8 });
    map2.put("der4",new int[] { 4,5,8 });
    map2.put("der1",new int[] { 1,3,8 });
    map2.put("der2",new int[] { 4,3,8 });
    table.put("PROV_DERIVATION",map2);
    map2=new HashMap<String, int[]>();
    map2.put("--1--",new int[] { 4,7 });
    map2.put("--0--",new int[] { 1,7 });
    table.put("PROV_ATTRIBUTION",map2);
    map2=new HashMap<String, int[]>();
    map2.put("--1--",new int[] { 4,8 });
    map2.put("--0--",new int[] { 1,8 });
    table.put("PROV_GENERATION",map2);
    map2=new HashMap<String, int[]>();
    map2.put("--1--",new int[] { 8,5 });
    map2.put("--0--",new int[] { 8,3 });
    table.put("PROV_USAGE",map2);
    return table;
  }

  public static String[] __getAllTypes() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateGetAllTypesMethodStatic;
    // in file CompilerCommon.java, at line 1839;
    String[] table=new String[6];
    table[0]="http://www.w3.org/ns/prov#Entity";
    table[1]="http://www.w3.org/ns/prov#Activity";
    table[2]="http://www.w3.org/ns/prov#Agent";
    table[3]="http://openprovenance.org/ns/fs#ApprovalRecord";
    table[4]="http://openprovenance.org/ns/fs#ApprovedPipeline";
    table[5]="http://openprovenance.org/ns/fs#ApprovingPipeline";
    return table;
  }

  /**
   * Returns a converter from Processor taking arguments to Processor taking record
   * @param __processor a transformer for this template
   * @param <T> type variable for the result of processor
   * @return File_approvingProcessor.org.openprovenance.book.fs.client.common&lt;T&gt;
   */
  public final <T> File_approvingProcessor<T> processorConverter(
      Function<Object[], T> __processor) {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateProcessorConverter;
    // in file CompilerCommon.java, at line 918;
    return (__approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end) -> {
          return __processor.apply(new Object[] { getFullyQualifiedName(),__approved_pipeline,__filename,__pipeline,__approval_record,__score,__approval_method,__manager,__approving,__signature,__path,__time,__start,__end });
        };
  }

  /**
   * Null method for composite
   * @return null
   */
  public String[] getOutputs() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateOutputsMethod;
    // in file CompilerCommon.java, at line 1221;
    return outputs;
  }

  /**
   * Null method for composite
   * @return null
   */
  public String[] getInputs() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateInputsMethod;
    // in file CompilerCommon.java, at line 1240;
    return inputs;
  }

  /**
   * Null method for composite
   * @return null
   */
  public String[] getCompulsoryInputs() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateCompulsoryInputsMethod;
    // in file CompilerCommon.java, at line 1230;
    return compulsoryInputs;
  }

  public static File_approvingBean examplar() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateExamplarBean;
    // in file CompilerCommon.java, at line 2079;
    File_approvingBean bean=new File_approvingBean();
    bean.approved_pipeline=Integer.valueOf("130");
    bean.pipeline=Integer.valueOf("118");
    bean.approval_record=Integer.valueOf("9885");
    bean.score=Integer.valueOf("356");
    bean.approval_method=Integer.valueOf("222");
    bean.manager=Integer.valueOf("12345");
    bean.approving=Integer.valueOf("12345");
    bean.filename="file/130-approved.pipeline";
    bean.signature="test2_signature";
    bean.path="test2_path";
    bean.time="2026-09-13T12:16:24.737+01:00";
    bean.start="2026-09-13T12:16:24.737+01:00";
    bean.end="2026-09-13T12:16:24.737+01:00";
    return bean;
  }

  /**
   * Returns a converter from Processor taking arguments to Processor taking record
   * @param processor a transformer for this template
   * @param <T> type variable for the result of processor
   * @return ProcessorArgsInterface.org.openprovenance.prov.client&lt;T&gt;
   */
  public final <T> Function<Object[], T> processorConverter(File_approvingProcessor<T> processor) {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateProcessorConverter2;
    // in file CompilerCommon.java, at line 979;
    return record -> {
          return processor.process(((record[1] == null) ? null : ((record[1] instanceof String) ? Integer.valueOf((String)record[1]) : (Integer)record[1])),(String)record[2],((record[3] == null) ? null : ((record[3] instanceof String) ? Integer.valueOf((String)record[3]) : (Integer)record[3])),((record[4] == null) ? null : ((record[4] instanceof String) ? Integer.valueOf((String)record[4]) : (Integer)record[4])),((record[5] == null) ? null : ((record[5] instanceof String) ? Integer.valueOf((String)record[5]) : (Integer)record[5])),((record[6] == null) ? null : ((record[6] instanceof String) ? Integer.valueOf((String)record[6]) : (Integer)record[6])),((record[7] == null) ? null : ((record[7] instanceof String) ? Integer.valueOf((String)record[7]) : (Integer)record[7])),((record[8] == null) ? null : ((record[8] instanceof String) ? Integer.valueOf((String)record[8]) : (Integer)record[8])),(String)record[9],(String)record[10],(String)record[11],(String)record[12],(String)record[13]);
        };
  }

  public static File_approvingBean args2bean(Integer __approved_pipeline, String __filename,
      Integer __pipeline, Integer __approval_record, Integer __score, Integer __approval_method,
      Integer __manager, Integer __approving, String __signature, String __path, String __time,
      String __start, String __end) {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateFactoryMethodWithBean;
    // in file CompilerCommon.java, at line 1888;
    File_approvingBean bean=new File_approvingBean();
    bean.approved_pipeline=__approved_pipeline;
    bean.filename=__filename;
    bean.pipeline=__pipeline;
    bean.approval_record=__approval_record;
    bean.score=__score;
    bean.approval_method=__approval_method;
    bean.manager=__manager;
    bean.approving=__approving;
    bean.signature=__signature;
    bean.path=__path;
    bean.time=__time;
    bean.start=__start;
    bean.end=__end;
    return bean;
  }

  /**
   * logFile_approving client side logging method
   * @return File_approvingProcessor
   */
  public File_approvingProcessor<String> bean2sql() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateBeanToSqlConversionMethod;
    // in file CompilerCommon.java, at line 854;
    File_approvingBuilder self=this;
    return (__approved_pipeline, __filename, __pipeline, __approval_record, __score, __approval_method, __manager, __approving, __signature, __path, __time, __start, __end) -> {
          StringBuilder sb=new StringBuilder();
          self.sqlTuple(sb,__approved_pipeline,__filename,__pipeline,__approval_record,__score,__approval_method,__manager,__approving,__signature,__path,__time,__start,__end);
          return sb.toString();
        };
  }

  public void sqlTuple(StringBuilder sb, Integer __approved_pipeline, String __filename,
      Integer __pipeline, Integer __approval_record, Integer __score, Integer __approval_method,
      Integer __manager, Integer __approving, String __signature, String __path, String __time,
      String __start, String __end) {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerSQL, method generateSqlTupleMethod;
    // in file CompilerSQL.java, at line 361;
    sb.append("(");
    if ((__approved_pipeline == null)) {
      sb.append("''");
    } else {
      sb.append("");
      sb.append(__approved_pipeline);
    }
    sb.append(",");
    if ((__filename == null)) {
      sb.append("''");
    } else {
      sb.append("'");
      sb.append(__filename);
      sb.append("'");
    }
    sb.append(",");
    if ((__pipeline == null)) {
      sb.append("''");
    } else {
      sb.append("");
      sb.append(__pipeline);
    }
    sb.append(",");
    if ((__approval_record == null)) {
      sb.append("''");
    } else {
      sb.append("");
      sb.append(__approval_record);
    }
    sb.append(",");
    if ((__score == null)) {
      sb.append("''");
    } else {
      sb.append("");
      sb.append(__score);
    }
    sb.append(",");
    if ((__approval_method == null)) {
      sb.append("''");
    } else {
      sb.append("");
      sb.append(__approval_method);
    }
    sb.append(",");
    if ((__manager == null)) {
      sb.append("''");
    } else {
      sb.append("");
      sb.append(__manager);
    }
    sb.append(",");
    if ((__approving == null)) {
      sb.append("''");
    } else {
      sb.append("");
      sb.append(__approving);
    }
    sb.append(",");
    if ((__signature == null)) {
      sb.append("''");
    } else {
      sb.append("'");
      sb.append(__signature);
      sb.append("'");
    }
    sb.append(",");
    if ((__path == null)) {
      sb.append("''");
    } else {
      sb.append("'");
      sb.append(__path);
      sb.append("'");
    }
    sb.append(",");
    if ((__time == null)) {
      sb.append("''");
    } else {
      sb.append("'");
      sb.append(__time);
      sb.append("'");
    }
    sb.append(",");
    if ((__start == null)) {
      sb.append("''");
    } else {
      sb.append("'");
      sb.append(__start);
      sb.append("'");
    }
    sb.append(",");
    if ((__end == null)) {
      sb.append("''");
    } else {
      sb.append("'");
      sb.append(__end);
      sb.append("'");
    }
    sb.append(")");
  }

  public final File_approvingIntegratorBuilder getIntegrator() {
    // Generated by class org.openprovenance.prov.template.compiler.common.CompilerCommon, method generateMethodGetIntegrator;
    // in file CompilerCommon.java, at line 228;
    return __integrator;
  }
}
