// Generated automatically by ProvToolbox for template configuration 'fs_template_library'
// by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateBean,
// in file CompilerBeanGenerator.java, at line 59
package org.openprovenance.book.fs.client.integrator;

import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.LinkedList;
import java.util.List;

/**
 * A composite bean for file_transforming_composite that only contains the outputs of this template.
 */
public class File_transforming_compositeOutputs {
  /**
   * The template name
   */
  public final String isA = "org.openprovenance.templates.fs.FileTransformingComposite";

  /**
   * Allows for database key to be returned.
   */
  public Integer ID;

  /**
   * bean: The bean identifier (not used for now) (expected type: xsd:string)
   */
  public String bean;

  /**
   * count: The number of records being composed (calculated automatically) (expected type: xsd:int)
   */
  public Integer count;

  /**
   * type: The type of bean being composed (expected type: xsd:string)
   */
  public String type;

  /**
   * List of composed templates generated Automatically by ProvToolbox (CompilerBeanGenerator.generateCompositeList()) for template org.openprovenance.templates.fs.FileTransforming.
   */
  public List<File_transformingOutputs> __elements = new LinkedList<>();

  /**
   * Class of elements inside this composite
   */
  public String consistsOf = "org.openprovenance.book.fs.client.integrator.File_transformingOutputs";

  public <T> T process(File_transforming_compositeOutputsProcessor<T> __processor) {
    // PAST generator method. Created by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateInvokeProcessor;
    // in file CompilerBeanGenerator.java, at line 693;
    return __processor.process(bean,count,type,__elements);
  }

  public void addElements(Object o) {
    // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanGenerator, method generateCompositeListExtender;
    // in file CompilerBeanGenerator.java, at line 668;
    __elements.add((File_transformingOutputs)o);
  }
}
