// Generated by ProvToolbox for template configuration 'PleadWorkflow'
// by class org.openprovenance.bookptm.workflows.GeneratePleadWorkflow, method generateAndCompilePast,
// in file GeneratePleadWorkflow.java, at line 496

const { File_transformingInputs } = require('org/openprovenance/book/fs/client/integrator/File_transformingInputs.js');
const { File_filteringInputs } = require('org/openprovenance/book/fs/client/integrator/File_filteringInputs.js');
const { File_trainingInputs } = require('org/openprovenance/book/fs/client/integrator/File_trainingInputs.js');
const { File_approvingInputs } = require('org/openprovenance/book/fs/client/integrator/File_approvingInputs.js');
const { File_validatingInputs } = require('org/openprovenance/book/fs/client/integrator/File_validatingInputs.js');
const { File_splittingInputs } = require('org/openprovenance/book/fs/client/integrator/File_splittingInputs.js');

class PleadWorkflow {
  constructor(templateInstantiation, inputs, outputs) {
    this.templateInstantiation = templateInstantiation;
    this.inputs = inputs;
    this.outputs = outputs;
  }

  workflow(engineer, manager, filenameRoot, oldFileId, tmethod, fmethod, n_rows, n_cols, path, start, end) {
    // 
    // Transforming
    // 
    let transformingInputs = new File_transformingInputs();
    transformingInputs.filename = filenameRoot + "-transformed.csv";
    transformingInputs.file = oldFileId;
    transformingInputs.method = tmethod;
    transformingInputs.engineer = engineer;
    transformingInputs.path = path;
    transformingInputs.time = this.time();
    transformingInputs.start = start;
    transformingInputs.end = end;
    if (this.inputs != null) {
      this.inputs.push(transformingInputs);
    }
    let transformingOutputs = this.templateInstantiation.process_file_transforming_inputs(transformingInputs);
    if (this.outputs != null) {
      this.outputs.push(transformingOutputs);
    }
    // 
    // Filtering
    // 
    let filteringInputs = new File_filteringInputs();
    filteringInputs.filename = filenameRoot + "-filtered.csv";
    filteringInputs.file = transformingOutputs.transformed_file;
    filteringInputs.method = fmethod;
    filteringInputs.engineer = engineer;
    filteringInputs.n_rows = n_rows;
    filteringInputs.n_cols = n_cols;
    filteringInputs.path = path;
    filteringInputs.time = this.time();
    filteringInputs.start = start;
    filteringInputs.end = end;
    if (this.inputs != null) {
      this.inputs.push(filteringInputs);
    }
    let filteringOutputs = this.templateInstantiation.process_file_filtering_inputs(filteringInputs);
    if (this.outputs != null) {
      this.outputs.push(filteringOutputs);
    }
    // 
    // Splitting
    // 
    let splittingInputs = new File_splittingInputs();
    splittingInputs.filename1 = filenameRoot + "-training.csv";
    splittingInputs.filename2 = filenameRoot + "-validation.csv";
    splittingInputs.file = filteringOutputs.filtered_file;
    splittingInputs.engineer = engineer;
    splittingInputs.path1 = path;
    splittingInputs.time = this.time();
    if (this.inputs != null) {
      this.inputs.push(splittingInputs);
    }
    let splittingOutputs = this.templateInstantiation.process_file_splitting_inputs(splittingInputs);
    if (this.outputs != null) {
      this.outputs.push(splittingOutputs);
    }
    // 
    // Training
    // 
    let trainingInputs = new File_trainingInputs();
    trainingInputs.filename = filenameRoot + ".pipeline";
    trainingInputs.training_dataset = splittingOutputs.split_file1;
    trainingInputs.engineer = engineer;
    trainingInputs.path = path;
    trainingInputs.time = this.time();
    if (this.inputs != null) {
      this.inputs.push(trainingInputs);
    }
    let trainingOutputs = this.templateInstantiation.process_file_training_inputs(trainingInputs);
    if (this.outputs != null) {
      this.outputs.push(trainingOutputs);
    }
    // 
    // Validating
    // 
    let validatingInputs = new File_validatingInputs();
    validatingInputs.score_value = 0.123;
    validatingInputs.testing_dataset = splittingOutputs.split_file2;
    validatingInputs.engineer = engineer;
    validatingInputs.path = path;
    validatingInputs.time = this.time();
    if (this.inputs != null) {
      this.inputs.push(validatingInputs);
    }
    let validatingOutputs = this.templateInstantiation.process_file_validating_inputs(validatingInputs);
    if (this.outputs != null) {
      this.outputs.push(validatingOutputs);
    }
    // 
    // Approving
    // 
    let approvingInputs = new File_approvingInputs();
    approvingInputs.pipeline = trainingOutputs.pipeline;
    approvingInputs.filename = filenameRoot + ".approved-pipeline";
    approvingInputs.score = validatingOutputs.score;
    approvingInputs.signature = "signature";
    approvingInputs.manager = manager;
    approvingInputs.path = path;
    approvingInputs.time = this.time();
    if (this.inputs != null) {
      this.inputs.push(approvingInputs);
    }
    let approvingOutputs = this.templateInstantiation.process_file_approving_inputs(approvingInputs);
    if (this.outputs != null) {
      this.outputs.push(approvingOutputs);
    }
  }

  time() {
  }

}

module.exports = { PleadWorkflow,  };
