# Generated by ProvToolbox for template configuration 'PleadWorkflow'
# by class org.openprovenance.bookptm.workflows.GeneratePleadWorkflow, method generateAndCompilePast,
# in file GeneratePleadWorkflow.java, at line 496

from org.openprovenance.book.fs.client.integrator.File_splittingInputs import File_splittingInputs
from past.util.Map import Map
from org.openprovenance.book.fs.client.integrator.File_validatingInputs import File_validatingInputs
from past.util.List import List
from org.openprovenance.book.fs.client.integrator.File_approvingInputs import File_approvingInputs
from org.openprovenance.book.fs.client.integrator.File_trainingInputs import File_trainingInputs
from org.openprovenance.book.fs.client.integrator.File_filteringInputs import File_filteringInputs
from org.openprovenance.book.fs.client.integrator.File_transformingInputs import File_transformingInputs


""""""
class PleadWorkflow:
    def __init__(self, templateInstantiation, inputs, outputs):
        self.templateInstantiation = templateInstantiation
        self.inputs = inputs
        self.outputs = outputs
        pass

    def workflow(self, engineer, manager, filenameRoot, oldFileId, tmethod, fmethod, n_rows, n_cols, path, start, end):
        # 
        # Transforming
        # 
        transformingInputs = File_transformingInputs()
        transformingInputs.filename = filenameRoot + "-transformed.csv"
        transformingInputs.file = oldFileId
        transformingInputs.method = tmethod
        transformingInputs.engineer = engineer
        transformingInputs.path = path
        transformingInputs.time = self.time()
        transformingInputs.start = start
        transformingInputs.end = end
        if self.inputs != 0:
            self.inputs.append(transformingInputs)
        transformingOutputs = self.templateInstantiation.process_file_transforming_inputs(transformingInputs)
        if self.outputs != 0:
            self.outputs.append(transformingOutputs)
        # 
        # Filtering
        # 
        filteringInputs = File_filteringInputs()
        filteringInputs.filename = filenameRoot + "-filtered.csv"
        filteringInputs.file = transformingOutputs.transformed_file
        filteringInputs.method = fmethod
        filteringInputs.engineer = engineer
        filteringInputs.n_rows = n_rows
        filteringInputs.n_cols = n_cols
        filteringInputs.path = path
        filteringInputs.time = self.time()
        filteringInputs.start = start
        filteringInputs.end = end
        if self.inputs != 0:
            self.inputs.append(filteringInputs)
        filteringOutputs = self.templateInstantiation.process_file_filtering_inputs(filteringInputs)
        if self.outputs != 0:
            self.outputs.append(filteringOutputs)
        # 
        # Splitting
        # 
        splittingInputs = File_splittingInputs()
        splittingInputs.filename1 = filenameRoot + "-training.csv"
        splittingInputs.filename2 = filenameRoot + "-validation.csv"
        splittingInputs.file = filteringOutputs.filtered_file
        splittingInputs.engineer = engineer
        splittingInputs.path1 = path
        splittingInputs.time = self.time()
        if self.inputs != 0:
            self.inputs.append(splittingInputs)
        splittingOutputs = self.templateInstantiation.process_file_splitting_inputs(splittingInputs)
        if self.outputs != 0:
            self.outputs.append(splittingOutputs)
        # 
        # Training
        # 
        trainingInputs = File_trainingInputs()
        trainingInputs.filename = filenameRoot + ".pipeline"
        trainingInputs.training_dataset = splittingOutputs.split_file1
        trainingInputs.engineer = engineer
        trainingInputs.path = path
        trainingInputs.time = self.time()
        if self.inputs != 0:
            self.inputs.append(trainingInputs)
        trainingOutputs = self.templateInstantiation.process_file_training_inputs(trainingInputs)
        if self.outputs != 0:
            self.outputs.append(trainingOutputs)
        # 
        # Validating
        # 
        validatingInputs = File_validatingInputs()
        validatingInputs.score_value = 0.123
        validatingInputs.testing_dataset = splittingOutputs.split_file2
        validatingInputs.engineer = engineer
        validatingInputs.path = path
        validatingInputs.time = self.time()
        if self.inputs != 0:
            self.inputs.append(validatingInputs)
        validatingOutputs = self.templateInstantiation.process_file_validating_inputs(validatingInputs)
        if self.outputs != 0:
            self.outputs.append(validatingOutputs)
        # 
        # Approving
        # 
        approvingInputs = File_approvingInputs()
        approvingInputs.pipeline = trainingOutputs.pipeline
        approvingInputs.filename = filenameRoot + ".approved-pipeline"
        approvingInputs.score = validatingOutputs.score
        approvingInputs.signature = "signature"
        approvingInputs.manager = manager
        approvingInputs.path = path
        approvingInputs.time = self.time()
        if self.inputs != 0:
            self.inputs.append(approvingInputs)
        approvingOutputs = self.templateInstantiation.process_file_approving_inputs(approvingInputs)
        if self.outputs != 0:
            self.outputs.append(approvingOutputs)
        pass

    def time(self):
        pass

    inputs = None
    outputs = None
    templateInstantiation = None
