#!/usr/bin/env python3
"""openprov-schema.json: the PROV-JSONLD schema extended with the openprov context's terms.

JSON Schema (draft-07) has no override, so the extension is written by reference: every definition
of the specification's schema that does not change is a $ref into the published schema, and only
what changes is restated here, derived from the specification's text:

  - the relations the openprov context scopes terms to (Attribution, Membership, Specialization,
    Communication): the specification's definition, plus one property per scoped term, a
    QualifiedName+ like the relation's own references, since the terms are @type: @id;
  - the dispatch chain from a document to its statements (Document, Bundle, StatementOrBundle,
    Statement), because the specification's chain would route a relation to the specification's
    definition of it.

Usage: schema-extend.py <spec-schema.json> <openprov.jsonld> <out.json>
"""
import json
import sys
from collections import OrderedDict

SPEC = "https://openprovenance.org/prov-jsonld/schema.json"
OUT_ID = "https://openprovenance.org/ns/openprov-schema.json"
CHAIN = ["prov:Document", "prov:Bundle", "prov:StatementOrBundle", "prov:Statement"]


def scopes(context):
    """The scoped types of the openprov context, each with its openprov terms in context order."""
    result = OrderedDict()
    for name, definition in context["@context"][1].items():
        if isinstance(definition, dict) and "@context" in definition:
            terms = [t for t, d in definition["@context"].items()
                     if isinstance(d, dict) and str(d.get("@id", "")).startswith("openprov:")]
            result["prov:" + name] = terms
    return result


def rewire(node, local):
    """A copy of a definition whose internal references point into the published schema, unless local."""
    if isinstance(node, dict):
        out = OrderedDict()
        for k, v in node.items():
            if k == "$id":
                continue
            if k == "$ref" and isinstance(v, str) and v.startswith("#/definitions/"):
                out[k] = v if v[len("#/definitions/"):] in local else SPEC + v
            else:
                out[k] = rewire(v, local)
        return out
    if isinstance(node, list):
        return [rewire(x, local) for x in node]
    return node


def extend(spec, context):
    scoped = scopes(context)
    local = set(CHAIN) | set(scoped)
    definitions = OrderedDict()
    for name in CHAIN:
        definitions[name] = rewire(spec["definitions"][name], local)
    for name, terms in scoped.items():
        d = rewire(spec["definitions"][name], local)
        for term in terms:
            d["properties"][term] = {"$ref": SPEC + "#/definitions/QualifiedName+"}
        definitions[name] = d
    return OrderedDict([
        ("$schema", spec["$schema"]),
        ("$id", OUT_ID),
        ("title", "PROV-JSONLD with the OpenProv vocabulary"),
        ("description", "The PROV-JSONLD schema, " + SPEC + ", with the terms https://openprovenance.org/ns/openprov.jsonld scopes to an attribution, a membership, a specialization or a communication. Unchanged definitions are referenced, not restated. Generated by schema-extend.py."),
        ("$ref", "#/definitions/prov:Document"),
        ("definitions", definitions),
    ])


if __name__ == "__main__":
    spec_file, context_file, out_file = sys.argv[1:4]
    with open(spec_file) as f:
        spec = json.load(f, object_pairs_hook=OrderedDict)
    with open(context_file) as f:
        context = json.load(f, object_pairs_hook=OrderedDict)
    with open(out_file, "w") as f:
        json.dump(extend(spec, context), f, indent=2)
        f.write("\n")
    print("Written:", out_file)
