// Generated by ProvToolbox for template configuration 'BeanLocalEnactor3'
// by class org.openprovenance.prov.template.compiler.CompilerIdentifierRegistry, method generateBeanLocalEnactor3,
// in file CompilerIdentifierRegistry.java, at line 177

const { BeanHistory } = require('org/openprovenance/templates/catalogue/fs/integrator/BeanHistory.js');
const { WebTemplateInvoker } = require('./fs_WebTemplateInvoker2.js');

class RemoteEnactor extends BeanHistory {
  constructor(url, accessToken) {
    super(new WebTemplateInvoker(url, accessToken), []);

  }

}

module.exports = { RemoteEnactor,  };
